'use client';

import { toast } from 'sonner';

/**
 * Export comparison results as a printable HTML report.
 * Opens a new window with a print-friendly layout that can be saved as PDF.
 *
 * Usage:
 *   exportComparisonReport('Multi-Structure Comparison', htmlContent);
 */

export function exportComparisonReport(title: string, tableHtml: string) {
  const reportWindow = window.open('', '_blank', 'width=900,height=700');
  if (!reportWindow) {
    toast.error('Failed to open report window — please allow popups');
    return;
  }

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} — PDB Tracker Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      color: #1a1a1a;
      background: #fff;
      padding: 40px;
      line-height: 1.5;
    }
    h1 {
      font-size: 20px;
      margin-bottom: 4px;
      color: #c96442;
    }
    .meta {
      font-size: 11px;
      color: #888;
      margin-bottom: 20px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 12px;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 6px 10px;
      text-align: left;
      vertical-align: top;
    }
    th {
      background: #f5f0ea;
      font-weight: 600;
      font-size: 10px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    td:first-child {
      font-weight: 600;
      background: #faf7f4;
      font-size: 10px;
      text-transform: uppercase;
    }
    .best {
      color: #16a34a;
      font-weight: bold;
    }
    .best-badge {
      font-size: 8px;
      background: #16a34a;
      color: #fff;
      padding: 1px 4px;
      border-radius: 3px;
      margin-left: 4px;
    }
    .footer {
      margin-top: 30px;
      padding-top: 10px;
      border-top: 1px solid #ddd;
      font-size: 10px;
      color: #aaa;
    }
    @media print {
      body { padding: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div class="meta">Generated by PDB Structure Tracker · ${new Date().toLocaleString()}</div>
  ${tableHtml}
  <div class="footer">PDB Structure Tracker v5 · ${new Date().toISOString().slice(0, 10)}</div>
  <div class="no-print" style="margin-top:20px;text-align:center;">
    <button onclick="window.print()" style="padding:8px 20px;background:#c96442;color:#fff;border:none;border-radius:6px;cursor:pointer;font-size:12px;">Print / Save as PDF</button>
  </div>
  <script>
    // Auto-open print dialog after load
    setTimeout(function() { window.print(); }, 500);
  </script>
</body>
</html>`;

  reportWindow.document.write(html);
  reportWindow.document.close();
  toast.success('Report generated', { description: 'Use Print dialog to save as PDF' });
}
