import type {
  PdbEntry,
  WeeklySnapshot,
  WeeklyReport,
  Evaluation,
  EvalPdbStructure,
  EvalBlastResult,
  LitPaper,
  LitPaperPdb,
  LitReport,
  LitStats,
} from '@/lib/pdb-types';

// ─── Fallback Snapshots (W01–W08) ────────────────────────────────────────────

export const FALLBACK_SNAPSHOTS: WeeklySnapshot[] = [
  {
    weekId: 'W01',
    weekStart: '2025-01-06',
    weekEnd: '2025-01-12',
    totalStructures: 312,
    methods: { 'X-RAY DIFFRACTION': 198, 'Cryo-EM': 89, 'SOLUTION NMR': 22, OTHER: 3 },
    date: '2025-01-06',
    cryoemCount: 89,
    xrayCount: 198,
    nmrCount: 22,
    otherCount: 3,
    avgResolution: 2.35,
    topJournals: JSON.stringify({ 'Nature': 5, 'Science': 3, 'Cell': 4, 'Nat. Struct. Mol. Biol.': 6 }),
    ifDist: JSON.stringify({ 'IF≥20': 12, 'IF≥10': 38, 'IF≥5': 95, 'IF<5': 167 }),
    createdAt: '2025-01-13T00:00:00.000Z',
    cryoemAvgRes: 3.21,
    xrayAvgRes: 1.92,
    cryoemResDist: JSON.stringify({ '<3Å': 28, '3-4Å': 41, '4-5Å': 15, '>5Å': 5 }),
    xrayResDist: JSON.stringify({ '<1.5Å': 22, '1.5-2Å': 68, '2-2.5Å': 62, '2.5-3Å': 35, '>3Å': 11 }),
  },
  {
    weekId: 'W02',
    weekStart: '2025-01-13',
    weekEnd: '2025-01-19',
    totalStructures: 287,
    methods: { 'X-RAY DIFFRACTION': 175, 'Cryo-EM': 82, 'SOLUTION NMR': 25, OTHER: 5 },
    date: '2025-01-13',
    cryoemCount: 82,
    xrayCount: 175,
    nmrCount: 25,
    otherCount: 5,
    avgResolution: 2.41,
    topJournals: JSON.stringify({ 'Nature': 4, 'Science': 2, 'Cell': 3, 'Nat. Commun.': 8 }),
    ifDist: JSON.stringify({ 'IF≥20': 9, 'IF≥10': 31, 'IF≥5': 88, 'IF<5': 159 }),
    createdAt: '2025-01-20T00:00:00.000Z',
    cryoemAvgRes: 3.45,
    xrayAvgRes: 1.88,
    cryoemResDist: JSON.stringify({ '<3Å': 22, '3-4Å': 38, '4-5Å': 17, '>5Å': 5 }),
    xrayResDist: JSON.stringify({ '<1.5Å': 18, '1.5-2Å': 58, '2-2.5Å': 55, '2.5-3Å': 32, '>3Å': 12 }),
  },
  {
    weekId: 'W03',
    weekStart: '2025-01-20',
    weekEnd: '2025-01-26',
    totalStructures: 345,
    methods: { 'X-RAY DIFFRACTION': 210, 'Cryo-EM': 98, 'SOLUTION NMR': 30, OTHER: 7 },
    date: '2025-01-20',
    cryoemCount: 98,
    xrayCount: 210,
    nmrCount: 30,
    otherCount: 7,
    avgResolution: 2.28,
    topJournals: JSON.stringify({ 'Nature': 6, 'Science': 4, 'Cell': 5, 'PNAS': 7 }),
    ifDist: JSON.stringify({ 'IF≥20': 15, 'IF≥10': 42, 'IF≥5': 108, 'IF<5': 180 }),
    createdAt: '2025-01-27T00:00:00.000Z',
    cryoemAvgRes: 3.05,
    xrayAvgRes: 1.85,
    cryoemResDist: JSON.stringify({ '<3Å': 35, '3-4Å': 42, '4-5Å': 16, '>5Å': 5 }),
    xrayResDist: JSON.stringify({ '<1.5Å': 25, '1.5-2Å': 72, '2-2.5Å': 65, '2.5-3Å': 38, '>3Å': 10 }),
  },
  {
    weekId: 'W04',
    weekStart: '2025-01-27',
    weekEnd: '2025-02-02',
    totalStructures: 298,
    methods: { 'X-RAY DIFFRACTION': 182, 'Cryo-EM': 85, 'SOLUTION NMR': 24, OTHER: 7 },
    date: '2025-01-27',
    cryoemCount: 85,
    xrayCount: 182,
    nmrCount: 24,
    otherCount: 7,
    avgResolution: 2.39,
    topJournals: JSON.stringify({ 'Nature': 3, 'Science': 5, 'Cell': 2, 'Nat. Struct. Mol. Biol.': 5 }),
    ifDist: JSON.stringify({ 'IF≥20': 11, 'IF≥10': 35, 'IF≥5': 92, 'IF<5': 160 }),
    createdAt: '2025-02-03T00:00:00.000Z',
    cryoemAvgRes: 3.18,
    xrayAvgRes: 1.94,
    cryoemResDist: JSON.stringify({ '<3Å': 25, '3-4Å': 38, '4-5Å': 18, '>5Å': 4 }),
    xrayResDist: JSON.stringify({ '<1.5Å': 20, '1.5-2Å': 62, '2-2.5Å': 58, '2.5-3Å': 30, '>3Å': 12 }),
  },
  {
    weekId: 'W05',
    weekStart: '2025-02-03',
    weekEnd: '2025-02-09',
    totalStructures: 330,
    methods: { 'X-RAY DIFFRACTION': 195, 'Cryo-EM': 102, 'SOLUTION NMR': 26, OTHER: 7 },
    date: '2025-02-03',
    cryoemCount: 102,
    xrayCount: 195,
    nmrCount: 26,
    otherCount: 7,
    avgResolution: 2.31,
    topJournals: JSON.stringify({ 'Nature': 7, 'Science': 3, 'Cell': 6, 'eLife': 9 }),
    ifDist: JSON.stringify({ 'IF≥20': 14, 'IF≥10': 44, 'IF≥5': 102, 'IF<5': 170 }),
    createdAt: '2025-02-10T00:00:00.000Z',
    cryoemAvgRes: 2.98,
    xrayAvgRes: 1.87,
    cryoemResDist: JSON.stringify({ '<3Å': 38, '3-4Å': 40, '4-5Å': 18, '>5Å': 6 }),
    xrayResDist: JSON.stringify({ '<1.5Å': 24, '1.5-2Å': 65, '2-2.5Å': 60, '2.5-3Å': 34, '>3Å': 12 }),
  },
  {
    weekId: 'W06',
    weekStart: '2025-02-10',
    weekEnd: '2025-02-16',
    totalStructures: 275,
    methods: { 'X-RAY DIFFRACTION': 165, 'Cryo-EM': 78, 'SOLUTION NMR': 23, OTHER: 9 },
    date: '2025-02-10',
    cryoemCount: 78,
    xrayCount: 165,
    nmrCount: 23,
    otherCount: 9,
    avgResolution: 2.47,
    topJournals: JSON.stringify({ 'Nature': 4, 'Science': 2, 'Cell': 3, 'Nat. Methods': 4 }),
    ifDist: JSON.stringify({ 'IF≥20': 10, 'IF≥10': 33, 'IF≥5': 85, 'IF<5': 147 }),
    createdAt: '2025-02-17T00:00:00.000Z',
    cryoemAvgRes: 3.52,
    xrayAvgRes: 1.96,
    cryoemResDist: JSON.stringify({ '<3Å': 20, '3-4Å': 35, '4-5Å': 17, '>5Å': 6 }),
    xrayResDist: JSON.stringify({ '<1.5Å': 16, '1.5-2Å': 55, '2-2.5Å': 52, '2.5-3Å': 28, '>3Å': 14 }),
  },
  {
    weekId: 'W07',
    weekStart: '2025-02-17',
    weekEnd: '2025-02-23',
    totalStructures: 356,
    methods: { 'X-RAY DIFFRACTION': 215, 'Cryo-EM': 105, 'SOLUTION NMR': 28, OTHER: 8 },
    date: '2025-02-17',
    cryoemCount: 105,
    xrayCount: 215,
    nmrCount: 28,
    otherCount: 8,
    avgResolution: 2.26,
    topJournals: JSON.stringify({ 'Nature': 8, 'Science': 4, 'Cell': 5, 'PNAS': 6 }),
    ifDist: JSON.stringify({ 'IF≥20': 16, 'IF≥10': 48, 'IF≥5': 112, 'IF<5': 180 }),
    createdAt: '2025-02-24T00:00:00.000Z',
    cryoemAvgRes: 2.92,
    xrayAvgRes: 1.83,
    cryoemResDist: JSON.stringify({ '<3Å': 40, '3-4Å': 42, '4-5Å': 17, '>5Å': 6 }),
    xrayResDist: JSON.stringify({ '<1.5Å': 28, '1.5-2Å': 75, '2-2.5Å': 62, '2.5-3Å': 36, '>3Å': 14 }),
  },
  {
    weekId: 'W08',
    weekStart: '2025-02-24',
    weekEnd: '2025-03-02',
    totalStructures: 320,
    methods: { 'X-RAY DIFFRACTION': 190, 'Cryo-EM': 95, 'SOLUTION NMR': 27, OTHER: 8 },
    date: '2025-02-24',
    cryoemCount: 95,
    xrayCount: 190,
    nmrCount: 27,
    otherCount: 8,
    avgResolution: 2.33,
    topJournals: JSON.stringify({ 'Nature': 5, 'Science': 3, 'Cell': 4, 'Nat. Commun.': 7 }),
    ifDist: JSON.stringify({ 'IF≥20': 13, 'IF≥10': 40, 'IF≥5': 98, 'IF<5': 169 }),
    createdAt: '2025-03-03T00:00:00.000Z',
    cryoemAvgRes: 3.10,
    xrayAvgRes: 1.89,
    cryoemResDist: JSON.stringify({ '<3Å': 32, '3-4Å': 40, '4-5Å': 18, '>5Å': 5 }),
    xrayResDist: JSON.stringify({ '<1.5Å': 22, '1.5-2Å': 68, '2-2.5Å': 58, '2.5-3Å': 32, '>3Å': 10 }),
  },
];

// ─── Fallback PDB Entries (55 entries) ────────────────────────────────────────

const ENTRY_TEMPLATES: Array<{
  pdbId: string;
  method: string;
  resolution: number | null;
  title: string;
  doi: string;
  journal: string;
  journalIf: number;
  authors: string;
  organisms: string;
  ligands: string | null;
  weekId: string;
  pubmedId: string;
  isCryoem: boolean;
  isXray: boolean;
  ifTier: string;
}> = [
  // Cryo-EM entries
  { pdbId: '8V9A', method: 'Cryo-EM', resolution: 3.2, title: 'Cryo-EM structure of human mTORC1 complex bound to Rag GTPases', doi: '10.1038/s41586-024-07812-3', journal: 'Nature', journalIf: 64.8, authors: 'Zhang Y, Wang L, Chen H, Liu X, Zhao M', organisms: 'Homo sapiens', ligands: 'ATP,MG', weekId: 'W01', pubmedId: '38912345', isCryoem: true, isXray: false, ifTier: 'IF≥20' },
  { pdbId: '8V9B', method: 'Cryo-EM', resolution: 2.8, title: 'Structure of the human spliceosome Bact complex at 2.8 Å resolution', doi: '10.1126/science.adq4567', journal: 'Science', journalIf: 56.9, authors: 'Johnson K, Patel R, Singh A, Kumar P', organisms: 'Homo sapiens', ligands: 'GDP', weekId: 'W01', pubmedId: '38912346', isCryoem: true, isXray: false, ifTier: 'IF≥20' },
  { pdbId: '8V9C', method: 'Cryo-EM', resolution: 3.5, title: 'Cryo-EM structure of the yeast ribosome-nascent chain complex', doi: '10.1016/j.cell.2024.07.012', journal: 'Cell', journalIf: 64.5, authors: 'Tanaka M, Suzuki K, Yamamoto T, Nakamura H', organisms: 'Saccharomyces cerevisiae', ligands: null, weekId: 'W01', pubmedId: '38912347', isCryoem: true, isXray: false, ifTier: 'IF≥20' },
  { pdbId: '8V9D', method: 'Cryo-EM', resolution: 4.1, title: 'Structure of the SARS-CoV-2 Omicron spike protein in prefusion state', doi: '10.1038/s41467-024-50123-4', journal: 'Nat. Commun.', journalIf: 16.6, authors: 'Li X, Wu J, Chen G, Yang F', organisms: 'Severe acute respiratory syndrome coronavirus 2', ligands: 'NAG,BMA', weekId: 'W02', pubmedId: '38922345', isCryoem: true, isXray: false, ifTier: 'IF≥10' },
  { pdbId: '8V9E', method: 'Cryo-EM', resolution: 3.0, title: 'Cryo-EM structure of the human BK channel in lipid nanodisc', doi: '10.1038/s41594-024-01345-2', journal: 'Nat. Struct. Mol. Biol.', journalIf: 16.8, authors: 'Kim S, Park J, Lee Y, Choi H', organisms: 'Homo sapiens', ligands: 'CA', weekId: 'W02', pubmedId: '38922346', isCryoem: true, isXray: false, ifTier: 'IF≥10' },
  { pdbId: '8V9F', method: 'Cryo-EM', resolution: 3.8, title: 'Structure of the Thermus thermophilus 70S ribosome with tRNA', doi: '10.1073/pnas.2401234567', journal: 'PNAS', journalIf: 11.1, authors: 'Ivanov A, Petrov B, Sokolova E, Morozov D', organisms: 'Thermus thermophilus', ligands: null, weekId: 'W03', pubmedId: '38932345', isCryoem: true, isXray: false, ifTier: 'IF≥10' },
  { pdbId: '8V9G', method: 'Cryo-EM', resolution: 2.6, title: 'High-resolution cryo-EM structure of human mitochondrial ATP synthase', doi: '10.1038/s41586-024-08012-7', journal: 'Nature', journalIf: 64.8, authors: 'Murphy B, Brown D, Wilson E, Taylor S', organisms: 'Homo sapiens', ligands: 'ADP,PO4', weekId: 'W03', pubmedId: '38932346', isCryoem: true, isXray: false, ifTier: 'IF≥20' },
  { pdbId: '8V9H', method: 'Cryo-EM', resolution: 4.5, title: 'Structure of the ER translocon-Sec61 complex with ribosome', doi: '10.7554/eLife.92345', journal: 'eLife', journalIf: 7.7, authors: 'Andersen C, Nielsen P, Jensen K, Larsen M', organisms: 'Homo sapiens', ligands: null, weekId: 'W04', pubmedId: '38942345', isCryoem: true, isXray: false, ifTier: 'IF≥5' },
  { pdbId: '8V9I', method: 'Cryo-EM', resolution: 3.3, title: 'Structure of human TFIIH transcription factor complex', doi: '10.1126/science.abq5678', journal: 'Science', journalIf: 56.9, authors: 'Garcia R, Martinez L, Lopez F, Torres J', organisms: 'Homo sapiens', ligands: 'ATP', weekId: 'W05', pubmedId: '38952345', isCryoem: true, isXray: false, ifTier: 'IF≥20' },
  { pdbId: '8V9J', method: 'Cryo-EM', resolution: 3.6, title: 'Cryo-EM structure of the Anopheles gambiae odorant receptor', doi: '10.1038/s41586-024-08234-5', journal: 'Nature', journalIf: 64.8, authors: 'Omondi O, Mwangi P, Kiptoo K, Rotich J', organisms: 'Anopheles gambiae', ligands: 'DEET', weekId: 'W06', pubmedId: '38962345', isCryoem: true, isXray: false, ifTier: 'IF≥20' },
  { pdbId: '8V9K', method: 'Cryo-EM', resolution: 2.9, title: 'Cryo-EM structure of the human proteasome 19S regulatory particle', doi: '10.1016/j.molcel.2024.08.003', journal: 'Mol. Cell', journalIf: 16.0, authors: 'Chen W, Zhao Q, Sun H, Zhou J', organisms: 'Homo sapiens', ligands: 'UBQ', weekId: 'W07', pubmedId: '38972345', isCryoem: true, isXray: false, ifTier: 'IF≥10' },
  { pdbId: '8V9L', method: 'Cryo-EM', resolution: 3.1, title: 'Cryo-EM structure of the E. coli RNA polymerase elongation complex', doi: '10.1093/nar/gkae567', journal: 'Nucleic Acids Res.', journalIf: 16.7, authors: 'Shapiro N, Cohen R, Levy T, Avraham D', organisms: 'Escherichia coli', ligands: 'MG,MN', weekId: 'W08', pubmedId: '38982345', isCryoem: true, isXray: false, ifTier: 'IF≥10' },

  // X-ray entries
  { pdbId: '9A1B', method: 'X-RAY DIFFRACTION', resolution: 1.5, title: 'Crystal structure of human carbonic anhydrase IX in complex with inhibitor SLC-0111', doi: '10.1021/jacs.4c01234', journal: 'J. Am. Chem. Soc.', journalIf: 15.0, authors: 'Thompson A, Harris C, Lewis D, Clark E', organisms: 'Homo sapiens', ligands: 'SLC,ZN', weekId: 'W01', pubmedId: '38912348', isCryoem: false, isXray: true, ifTier: 'IF≥10' },
  { pdbId: '9A1C', method: 'X-RAY DIFFRACTION', resolution: 1.8, title: 'Crystal structure of the SARS-CoV-2 main protease with nirmatrelvir', doi: '10.1038/s41586-024-07923-1', journal: 'Nature', journalIf: 64.8, authors: 'Wang Z, Liu Q, Sun W, Zhang F', organisms: 'Severe acute respiratory syndrome coronavirus 2', ligands: 'NIU', weekId: 'W01', pubmedId: '38912349', isCryoem: false, isXray: true, ifTier: 'IF≥20' },
  { pdbId: '9A1D', method: 'X-RAY DIFFRACTION', resolution: 2.1, title: 'Crystal structure of human KRAS G12C in complex with sotorasib', doi: '10.1016/j.cell.2024.06.018', journal: 'Cell', journalIf: 64.5, authors: 'Moore R, Baker S, Wright P, Hill G', organisms: 'Homo sapiens', ligands: 'SO4,GDP', weekId: 'W01', pubmedId: '38912350', isCryoem: false, isXray: true, ifTier: 'IF≥20' },
  { pdbId: '9A1E', method: 'X-RAY DIFFRACTION', resolution: 1.2, title: 'Ultra-high-resolution structure of hen egg-white lysozyme at 1.2 Å', doi: '10.1107/S2059798324006789', journal: 'Acta Crystallogr. D', journalIf: 6.2, authors: 'Peterson J, Collins M, Evans T, Robinson K', organisms: 'Gallus gallus', ligands: 'NAG', weekId: 'W02', pubmedId: '38922347', isCryoem: false, isXray: true, ifTier: 'IF≥5' },
  { pdbId: '9A1F', method: 'X-RAY DIFFRACTION', resolution: 1.9, title: 'Crystal structure of Bacillus subtilis ribosomal protein S15', doi: '10.1016/j.jmb.2024.168567', journal: 'J. Mol. Biol.', journalIf: 5.3, authors: 'Novak J, Horvat M, Krajnc A, Zupan J', organisms: 'Bacillus subtilis', ligands: 'ZN', weekId: 'W02', pubmedId: '38922348', isCryoem: false, isXray: true, ifTier: 'IF≥5' },
  { pdbId: '9A1G', method: 'X-RAY DIFFRACTION', resolution: 2.3, title: 'Crystal structure of the Arabidopsis thaliana auxin receptor TIR1', doi: '10.1038/s41586-024-08345-3', journal: 'Nature', journalIf: 64.8, authors: 'Tanabe S, Nagata K, Onishi M, Fujita H', organisms: 'Arabidopsis thaliana', ligands: 'IAA', weekId: 'W03', pubmedId: '38932347', isCryoem: false, isXray: true, ifTier: 'IF≥20' },
  { pdbId: '9A1H', method: 'X-RAY DIFFRACTION', resolution: 1.6, title: 'Crystal structure of the Mycobacterium tuberculosis enoyl-ACP reductase InhA', doi: '10.1021/acs.jmedchem.4c00567', journal: 'J. Med. Chem.', journalIf: 7.3, authors: 'Nguyen T, Pham H, Tran V, Do Q', organisms: 'Mycobacterium tuberculosis', ligands: 'NAD,TCL', weekId: 'W03', pubmedId: '38932348', isCryoem: false, isXray: true, ifTier: 'IF≥5' },
  { pdbId: '9A1I', method: 'X-RAY DIFFRACTION', resolution: 2.0, title: 'Crystal structure of human PPAR-gamma ligand-binding domain with rosiglitazone', doi: '10.1016/j.ejmech.2024.116789', journal: 'Eur. J. Med. Chem.', journalIf: 6.0, authors: 'Costa A, Ferreira B, Santos C, Oliveira R', organisms: 'Homo sapiens', ligands: 'BRL', weekId: 'W04', pubmedId: '38942346', isCryoem: false, isXray: true, ifTier: 'IF≥5' },
  { pdbId: '9A1J', method: 'X-RAY DIFFRACTION', resolution: 1.7, title: 'Crystal structure of Staphylococcus aureus sortase A transpeptidase', doi: '10.1021/acs.biochem.4c00234', journal: 'Biochemistry', journalIf: 2.9, authors: 'Maresso J, Schneewind O, Missiakas D', organisms: 'Staphylococcus aureus', ligands: 'CA', weekId: 'W04', pubmedId: '38942347', isCryoem: false, isXray: true, ifTier: 'IF<5' },
  { pdbId: '9A1K', method: 'X-RAY DIFFRACTION', resolution: 1.4, title: 'High-resolution structure of Thermotoga maritima cellulase Cel5A', doi: '10.1016/j.str.2024.07.005', journal: 'Structure', journalIf: 4.8, authors: 'Brumm P, Land M, Mead D', organisms: 'Thermotoga maritima', ligands: 'GLC', weekId: 'W05', pubmedId: '38952346', isCryoem: false, isXray: true, ifTier: 'IF<5' },
  { pdbId: '9A1L', method: 'X-RAY DIFFRACTION', resolution: 2.2, title: 'Crystal structure of the human CDK2-cyclin A complex with dinaciclib', doi: '10.1038/s41467-024-51234-8', journal: 'Nat. Commun.', journalIf: 16.6, authors: 'Fischer P, End A, Kramer A, Muller T', organisms: 'Homo sapiens', ligands: 'DIN,ATP', weekId: 'W05', pubmedId: '38952347', isCryoem: false, isXray: true, ifTier: 'IF≥10' },
  { pdbId: '9A1M', method: 'X-RAY DIFFRACTION', resolution: 1.85, title: 'Crystal structure of human Bruton tyrosine kinase with ibrutinib', doi: '10.1126/scisignal.abq6789', journal: 'Sci. Signal.', journalIf: 7.3, authors: 'Wang J, Cheng Y, Wei X, Zhao H', organisms: 'Homo sapiens', ligands: 'IBR', weekId: 'W06', pubmedId: '38962346', isCryoem: false, isXray: true, ifTier: 'IF≥5' },
  { pdbId: '9A1N', method: 'X-RAY DIFFRACTION', resolution: 1.95, title: 'Crystal structure of Plasmodium falciparum dihydroorotate dehydrogenase', doi: '10.1371/journal.ppat.1012345', journal: 'PLoS Pathog.', journalIf: 6.7, authors: 'Muller S, Papmehl D, Duffey M', organisms: 'Plasmodium falciparum', ligands: 'FMN,BRE', weekId: 'W06', pubmedId: '38962347', isCryoem: false, isXray: true, ifTier: 'IF≥5' },
  { pdbId: '9A1O', method: 'X-RAY DIFFRACTION', resolution: 1.3, title: 'Sub-angstrom crystal structure of bovine trypsin with benzamidine', doi: '10.1107/S2059798324007890', journal: 'Acta Crystallogr. D', journalIf: 6.2, authors: 'Radisky E, Koshland D', organisms: 'Bos taurus', ligands: 'BEN', weekId: 'W07', pubmedId: '38972346', isCryoem: false, isXray: true, ifTier: 'IF≥5' },
  { pdbId: '9A1P', method: 'X-RAY DIFFRACTION', resolution: 2.4, title: 'Crystal structure of the human EGFR kinase domain with osimertinib', doi: '10.1158/2159-8290.CD-24-0123', journal: 'Cancer Discov.', journalIf: 29.5, authors: 'Yun C, Boggon T, Li Y, Eck M', organisms: 'Homo sapiens', ligands: 'OSI', weekId: 'W07', pubmedId: '38972347', isCryoem: false, isXray: true, ifTier: 'IF≥20' },
  { pdbId: '9A1Q', method: 'X-RAY DIFFRACTION', resolution: 1.65, title: 'Crystal structure of mouse acetylcholinesterase with donepezil', doi: '10.1021/acs.chemrest.4c00123', journal: 'Chem. Res. Toxicol.', journalIf: 3.8, authors: 'Sussman J, Harel M, Silman I', organisms: 'Mus musculus', ligands: 'DON', weekId: 'W08', pubmedId: '38982346', isCryoem: false, isXray: true, ifTier: 'IF<5' },
  { pdbId: '9A1R', method: 'X-RAY DIFFRACTION', resolution: 1.75, title: 'Crystal structure of Candida albicans dihydrofolate reductase', doi: '10.1021/acsinfecdis.4c00156', journal: 'ACS Infect. Dis.', journalIf: 4.0, authors: 'Paulsen J, Liu J, Bolstad D', organisms: 'Candida albicans', ligands: 'NAP,MTX', weekId: 'W08', pubmedId: '38982347', isCryoem: false, isXray: true, ifTier: 'IF<5' },

  // NMR entries
  { pdbId: '2N9A', method: 'SOLUTION NMR', resolution: null, title: 'NMR structure of the intrinsically disordered region of human p53 transactivation domain', doi: '10.1002/prot.26567', journal: 'Proteins', journalIf: 3.3, authors: 'Wells M, Tidow H, Rutherford TJ, Fersht AR', organisms: 'Homo sapiens', ligands: null, weekId: 'W01', pubmedId: '38912351', isCryoem: false, isXray: false, ifTier: 'IF<5' },
  { pdbId: '2N9B', method: 'SOLUTION NMR', resolution: null, title: 'NMR structure of the Ebola virus VP35 interferon inhibitory domain', doi: '10.1016/j.jmb.2024.168789', journal: 'J. Mol. Biol.', journalIf: 5.3, authors: 'Leung D, Bhatt A, Odaert B, Bhatt D', organisms: 'Zaire ebolavirus', ligands: 'DSR', weekId: 'W02', pubmedId: '38922349', isCryoem: false, isXray: false, ifTier: 'IF≥5' },
  { pdbId: '2N9C', method: 'SOLUTION NMR', resolution: null, title: 'Solution structure of the HIV-1 Nef protein SH3-binding domain', doi: '10.1371/journal.pone.0301234', journal: 'PLoS ONE', journalIf: 2.9, authors: 'Breuer S, Gerlach H, Kolaric M, Geyer M', organisms: 'Human immunodeficiency virus 1', ligands: null, weekId: 'W03', pubmedId: '38932349', isCryoem: false, isXray: false, ifTier: 'IF<5' },
  { pdbId: '2N9D', method: 'SOLUTION NMR', resolution: null, title: 'NMR structure of the Drosophila melanogaster Hox protein Abd-B homeodomain', doi: '10.1002/bip.23456', journal: 'Biopolymers', journalIf: 2.1, authors: 'Joshi R, Passner JM, Rohs R, Mann RS', organisms: 'Drosophila melanogaster', ligands: 'DNA', weekId: 'W04', pubmedId: '38942348', isCryoem: false, isXray: false, ifTier: 'IF<5' },
  { pdbId: '2N9E', method: 'SOLUTION NMR', resolution: null, title: 'Solution NMR structure of the mouse Notch1 ankyrin domain', doi: '10.1073/pnas.2402345678', journal: 'PNAS', journalIf: 11.1, authors: 'Lubman O, Bhatt D, Korver W, Bhatt A', organisms: 'Mus musculus', ligands: null, weekId: 'W05', pubmedId: '38952348', isCryoem: false, isXray: false, ifTier: 'IF≥10' },

  // More Cryo-EM entries
  { pdbId: '8V9M', method: 'Cryo-EM', resolution: 3.4, title: 'Structure of the human GABA-A receptor in complex with diazepam', doi: '10.1038/s41586-024-08567-6', journal: 'Nature', journalIf: 64.8, authors: 'Phulera S, Zhu H, Yu J, Bhatt D', organisms: 'Homo sapiens', ligands: 'DZP', weekId: 'W04', pubmedId: '38942349', isCryoem: true, isXray: false, ifTier: 'IF≥20' },
  { pdbId: '8V9N', method: 'Cryo-EM', resolution: 2.7, title: 'Cryo-EM structure of the human TRPV1 ion channel', doi: '10.1126/science.acd1234', journal: 'Science', journalIf: 56.9, authors: 'Liao M, Cao E, Julius D, Cheng Y', organisms: 'Homo sapiens', ligands: 'RTX,CPS', weekId: 'W05', pubmedId: '38952349', isCryoem: true, isXray: false, ifTier: 'IF≥20' },
  { pdbId: '8V9O', method: 'Cryo-EM', resolution: 3.9, title: 'Cryo-EM structure of the Plasmodium falciparum 80S ribosome', doi: '10.1038/s41594-024-01567-9', journal: 'Nat. Struct. Mol. Biol.', journalIf: 16.8, authors: 'Wong W, Bai X, Barcina I, Bhatt D', organisms: 'Plasmodium falciparum', ligands: null, weekId: 'W06', pubmedId: '38962348', isCryoem: true, isXray: false, ifTier: 'IF≥10' },
  { pdbId: '8V9P', method: 'Cryo-EM', resolution: 3.0, title: 'Structure of the human PIEZO1 mechanosensitive ion channel', doi: '10.1016/j.cell.2024.09.003', journal: 'Cell', journalIf: 64.5, authors: 'Zhao Q, Zhou H, Chi S, Wang Y', organisms: 'Homo sapiens', ligands: 'CHO', weekId: 'W07', pubmedId: '38972348', isCryoem: true, isXray: false, ifTier: 'IF≥20' },
  { pdbId: '8V9Q', method: 'Cryo-EM', resolution: 4.2, title: 'Structure of the Vibrio cholerae type VI secretion system', doi: '10.1038/s41564-024-01789-3', journal: 'Nat. Microbiol.', journalIf: 28.3, authors: 'Basler M, Pilhofer M, Bhatt D, Bhatt A', organisms: 'Vibrio cholerae', ligands: null, weekId: 'W08', pubmedId: '38982348', isCryoem: true, isXray: false, ifTier: 'IF≥20' },

  // More X-ray entries
  { pdbId: '9A1S', method: 'X-RAY DIFFRACTION', resolution: 2.5, title: 'Crystal structure of human beta-2 adrenergic receptor with carazolol', doi: '10.1038/s41586-024-08678-1', journal: 'Nature', journalIf: 64.8, authors: 'Rosenbaum D, Cherezov V, Hanson M, Bhatt D', organisms: 'Homo sapiens', ligands: 'CAU,CHO', weekId: 'W02', pubmedId: '38922350', isCryoem: false, isXray: true, ifTier: 'IF≥20' },
  { pdbId: '9A1T', method: 'X-RAY DIFFRACTION', resolution: 1.55, title: 'Crystal structure of the influenza neuraminidase N1 with oseltamivir', doi: '10.1021/jacs.4c03456', journal: 'J. Am. Chem. Soc.', journalIf: 15.0, authors: 'Xu R, Zhu X, McBride R, Wilson I', organisms: 'Influenza A virus', ligands: 'GRI', weekId: 'W03', pubmedId: '38932350', isCryoem: false, isXray: true, ifTier: 'IF≥10' },
  { pdbId: '9A1U', method: 'X-RAY DIFFRACTION', resolution: 2.15, title: 'Crystal structure of humanCheckpoint kinase 1 with inhibitor', doi: '10.1016/j.jmb.2024.168901', journal: 'J. Mol. Biol.', journalIf: 5.3, authors: 'Huber T, Bhatt D, Goldberg J, Bhatt A', organisms: 'Homo sapiens', ligands: 'ANP', weekId: 'W04', pubmedId: '38942350', isCryoem: false, isXray: true, ifTier: 'IF≥5' },
  { pdbId: '9A1V', method: 'X-RAY DIFFRACTION', resolution: 1.9, title: 'Crystal structure of rat monoamine oxidase B with selegiline', doi: '10.1021/acs.biochem.4c00345', journal: 'Biochemistry', journalIf: 2.9, authors: 'Binda C, Wang J, Li M, Bhatt D', organisms: 'Rattus norvegicus', ligands: 'RIP', weekId: 'W05', pubmedId: '38952350', isCryoem: false, isXray: true, ifTier: 'IF<5' },
  { pdbId: '9A1W', method: 'X-RAY DIFFRACTION', resolution: 1.35, title: 'Crystal structure of T4 lysozyme L99A mutant with benzene', doi: '10.1021/acs.jcim.4c00234', journal: 'J. Chem. Inf. Model.', journalIf: 5.7, authors: 'Morton A, Baase WA, Matthews BW', organisms: 'Enterobacteria phage T4', ligands: 'BNZ', weekId: 'W06', pubmedId: '38962349', isCryoem: false, isXray: true, ifTier: 'IF≥5' },
  { pdbId: '9A1X', method: 'X-RAY DIFFRACTION', resolution: 2.0, title: 'Crystal structure of human tankyrase 2 catalytic domain with XAV939', doi: '10.1016/j.str.2024.08.007', journal: 'Structure', journalIf: 4.8, authors: 'Lehti K, Bhatt D, Kelleher J, Bhatt A', organisms: 'Homo sapiens', ligands: 'XAV', weekId: 'W07', pubmedId: '38972349', isCryoem: false, isXray: true, ifTier: 'IF<5' },
  { pdbId: '9A1Y', method: 'X-RAY DIFFRACTION', resolution: 1.8, title: 'Crystal structure of Toxoplasma gondii calcium-dependent protein kinase 1', doi: '10.1371/journal.pntd.0012345', journal: 'PLoS Negl. Trop. Dis.', journalIf: 4.0, authors: 'Ojo KK, Bhatt D, Van Voorhis WC, Bhatt A', organisms: 'Toxoplasma gondii', ligands: 'ANP,CA', weekId: 'W08', pubmedId: '38982349', isCryoem: false, isXray: true, ifTier: 'IF<5' },

  // More NMR + additional mix
  { pdbId: '2N9F', method: 'SOLUTION NMR', resolution: null, title: 'NMR structure of the Caenorhabditis elegans sensory receptor kinase domain', doi: '10.1002/prot.26789', journal: 'Proteins', journalIf: 3.3, authors: 'Bhatt D, Robertson A, Bhatt A', organisms: 'Caenorhabditis elegans', ligands: 'ATP', weekId: 'W06', pubmedId: '38962350', isCryoem: false, isXray: false, ifTier: 'IF<5' },
  { pdbId: '2N9G', method: 'SOLUTION NMR', resolution: null, title: 'Solution structure of the Zika virus capsid protein dimerization domain', doi: '10.1021/biochem.4c00234', journal: 'Biochemistry', journalIf: 2.9, authors: 'Fontana J, Lopez C, Bhatt D', organisms: 'Zika virus', ligands: null, weekId: 'W07', pubmedId: '38972350', isCryoem: false, isXray: false, ifTier: 'IF<5' },
  { pdbId: '2N9H', method: 'SOLUTION NMR', resolution: null, title: 'NMR structure of the human autophagy protein ATG8 in complex with p62', doi: '10.1038/s41467-024-52345-1', journal: 'Nat. Commun.', journalIf: 16.6, authors: 'Kumar V, Bhatt D, Chang C, Bhatt A', organisms: 'Homo sapiens', ligands: null, weekId: 'W08', pubmedId: '38982350', isCryoem: false, isXray: false, ifTier: 'IF≥10' },

  // Additional varied entries
  { pdbId: '8V9R', method: 'Cryo-EM', resolution: 3.7, title: 'Cryo-EM structure of the human L-type calcium channel Cav1.1', doi: '10.1038/s41586-024-08789-8', journal: 'Nature', journalIf: 64.8, authors: 'Zhao Y, Huang G, Wu J, Yan N', organisms: 'Homo sapiens', ligands: 'CA,NAG', weekId: 'W03', pubmedId: '38932351', isCryoem: true, isXray: false, ifTier: 'IF≥20' },
  { pdbId: '8V9S', method: 'Cryo-EM', resolution: 4.0, title: 'Structure of the Saccharomyces cerevisiae NPC inner ring', doi: '10.1126/science.aef2345', journal: 'Science', journalIf: 56.9, authors: 'Kosinski J, Mosalaganti S, Bhatt D, Beck M', organisms: 'Saccharomyces cerevisiae', ligands: null, weekId: 'W04', pubmedId: '38942351', isCryoem: true, isXray: false, ifTier: 'IF≥20' },
  { pdbId: '8V9T', method: 'Cryo-EM', resolution: 3.2, title: 'Cryo-EM structure of the human ABCB1 multidrug transporter', doi: '10.1038/s41594-024-01678-0', journal: 'Nat. Struct. Mol. Biol.', journalIf: 16.8, authors: 'Kim J, Chen L, Bhatt D, Bhatt A', organisms: 'Homo sapiens', ligands: 'ATP', weekId: 'W05', pubmedId: '38952351', isCryoem: true, isXray: false, ifTier: 'IF≥10' },
  { pdbId: '8V9U', method: 'Cryo-EM', resolution: 2.5, title: 'High-resolution structure of the human 26S proteasome', doi: '10.1016/j.cell.2024.10.002', journal: 'Cell', journalIf: 64.5, authors: 'Bhatt D, Dong Y, Bhatt A, Finley D', organisms: 'Homo sapiens', ligands: 'UBQ,ATP', weekId: 'W06', pubmedId: '38962351', isCryoem: true, isXray: false, ifTier: 'IF≥20' },
  { pdbId: '8V9V', method: 'Cryo-EM', resolution: 3.6, title: 'Cryo-EM structure of the Drosophila melanogaster COPI vesicle coat', doi: '10.7554/eLife.93456', journal: 'eLife', journalIf: 7.7, authors: 'Dodonova S, Bhatt D, Briggs J', organisms: 'Drosophila melanogaster', ligands: null, weekId: 'W07', pubmedId: '38972351', isCryoem: true, isXray: false, ifTier: 'IF≥5' },
  { pdbId: '8V9W', method: 'Cryo-EM', resolution: 3.0, title: 'Structure of the human NLRP3 inflammasome ring complex', doi: '10.1038/s41586-024-08901-8', journal: 'Nature', journalIf: 64.8, authors: 'Sharif H, Wang L, Bhatt D, Bhatt A', organisms: 'Homo sapiens', ligands: 'ATP,MG', weekId: 'W08', pubmedId: '38982351', isCryoem: true, isXray: false, ifTier: 'IF≥20' },

  // More X-ray entries
  { pdbId: '9A1Z', method: 'X-RAY DIFFRACTION', resolution: 1.45, title: 'Crystal structure of the E. coli dihydrofolate reductase with methotrexate', doi: '10.1021/acs.biochem.4c00456', journal: 'Biochemistry', journalIf: 2.9, authors: 'Sawaya M, Kraut J', organisms: 'Escherichia coli', ligands: 'MTX,NAP', weekId: 'W01', pubmedId: '38912352', isCryoem: false, isXray: true, ifTier: 'IF<5' },
  { pdbId: '9A2A', method: 'X-RAY DIFFRACTION', resolution: 2.3, title: 'Crystal structure of the human JAK2 kinase domain with ruxolitinib', doi: '10.1158/0008-5472.CAN-24-0456', journal: 'Cancer Res.', journalIf: 11.2, authors: 'Bhatt D, Bhatt A, Bhatt M', organisms: 'Homo sapiens', ligands: 'RUX', weekId: 'W02', pubmedId: '38922351', isCryoem: false, isXray: true, ifTier: 'IF≥10' },
  { pdbId: '9A2B', method: 'X-RAY DIFFRACTION', resolution: 1.7, title: 'Crystal structure of the Pseudomonas aeruginosa elastase', doi: '10.1016/j.jmb.2024.169012', journal: 'J. Mol. Biol.', journalIf: 5.3, authors: 'Bhatt D, Bhatt A, Bhatt M', organisms: 'Pseudomonas aeruginosa', ligands: 'ZN', weekId: 'W03', pubmedId: '38932352', isCryoem: false, isXray: true, ifTier: 'IF≥5' },
  { pdbId: '9A2C', method: 'X-RAY DIFFRACTION', resolution: 1.6, title: 'Crystal structure of the human estrogen receptor alpha LBD with tamoxifen', doi: '10.1038/s41586-024-09012-9', journal: 'Nature', journalIf: 64.8, authors: 'Shiau A, Barstad D, Bhatt D, Bhatt A', organisms: 'Homo sapiens', ligands: 'OHT', weekId: 'W04', pubmedId: '38942352', isCryoem: false, isXray: true, ifTier: 'IF≥20' },
  { pdbId: '9A2D', method: 'X-RAY DIFFRACTION', resolution: 2.1, title: 'Crystal structure of the HIV-1 integrase catalytic core domain', doi: '10.1371/journal.pone.0302345', journal: 'PLoS ONE', journalIf: 2.9, authors: 'Dyda F, Hickman A, Jenkins T, Bhatt D', organisms: 'Human immunodeficiency virus 1', ligands: 'MG', weekId: 'W05', pubmedId: '38952352', isCryoem: false, isXray: true, ifTier: 'IF<5' },
  { pdbId: '9A2E', method: 'X-RAY DIFFRACTION', resolution: 1.5, title: 'Crystal structure of the human Aurora kinase A with alisertib', doi: '10.1021/acs.jmedchem.4c00678', journal: 'J. Med. Chem.', journalIf: 7.3, authors: 'Bhatt D, Bhatt A, Bhatt M', organisms: 'Homo sapiens', ligands: 'MLN', weekId: 'W06', pubmedId: '38962352', isCryoem: false, isXray: true, ifTier: 'IF≥5' },
  { pdbId: '9A2F', method: 'X-RAY DIFFRACTION', resolution: 1.88, title: 'Crystal structure of the rat voltage-gated potassium channel Kv1.2', doi: '10.1038/s41586-024-09123-2', journal: 'Nature', journalIf: 64.8, authors: 'Long S, Campbell E, MacKinnon R', organisms: 'Rattus norvegicus', ligands: 'K', weekId: 'W07', pubmedId: '38972352', isCryoem: false, isXray: true, ifTier: 'IF≥20' },
  { pdbId: '9A2G', method: 'X-RAY DIFFRACTION', resolution: 2.0, title: 'Crystal structure of human protein kinase CK2 with CX-4945', doi: '10.1016/j.ejmech.2024.117123', journal: 'Eur. J. Med. Chem.', journalIf: 6.0, authors: 'Bhatt D, Bhatt A, Bhatt M', organisms: 'Homo sapiens', ligands: 'CX5', weekId: 'W08', pubmedId: '38982352', isCryoem: false, isXray: true, ifTier: 'IF≥5' },

  // Additional entries to reach 55
  { pdbId: '8V9X', method: 'Cryo-EM', resolution: 3.3, title: 'Cryo-EM structure of the human SMN complex', doi: '10.1038/s41594-024-01789-1', journal: 'Nat. Struct. Mol. Biol.', journalIf: 16.8, authors: 'Bhatt D, Patel A, Bhatt A', organisms: 'Homo sapiens', ligands: 'SMN', weekId: 'W01', pubmedId: '38912353', isCryoem: true, isXray: false, ifTier: 'IF≥10' },
  { pdbId: '8V9Y', method: 'Cryo-EM', resolution: 4.3, title: 'Structure of the human innate immune STING signaling complex', doi: '10.1038/s41586-024-09234-5', journal: 'Nature', journalIf: 64.8, authors: 'Shang G, Zhang C, Bhatt D, Bhatt A', organisms: 'Homo sapiens', ligands: 'CGA', weekId: 'W02', pubmedId: '38922352', isCryoem: true, isXray: false, ifTier: 'IF≥20' },
  { pdbId: '8V9Z', method: 'Cryo-EM', resolution: 2.8, title: 'Cryo-EM structure of the human TREX2 exonuclease', doi: '10.1073/pnas.2403456789', journal: 'PNAS', journalIf: 11.1, authors: 'Bhatt D, Bhatt A, Bhatt M', organisms: 'Homo sapiens', ligands: 'MG', weekId: 'W03', pubmedId: '38932353', isCryoem: true, isXray: false, ifTier: 'IF≥10' },
  { pdbId: '9A2H', method: 'X-RAY DIFFRACTION', resolution: 1.4, title: 'Ultra-high-resolution structure of crambin at 1.4 Å', doi: '10.1107/S2059798324008901', journal: 'Acta Crystallogr. D', journalIf: 6.2, authors: 'Teeter M, Bhatt D', organisms: 'Crambe hispanica', ligands: null, weekId: 'W04', pubmedId: '38942353', isCryoem: false, isXray: true, ifTier: 'IF≥5' },
  { pdbId: '9A2I', method: 'X-RAY DIFFRACTION', resolution: 2.2, title: 'Crystal structure of human CDK4-cyclin D1 with palbociclib', doi: '10.1158/2159-8290.CD-24-0567', journal: 'Cancer Discov.', journalIf: 29.5, authors: 'Fry D, Harvey P, Bhatt D, Bhatt A', organisms: 'Homo sapiens', ligands: '6BI', weekId: 'W05', pubmedId: '38952353', isCryoem: false, isXray: true, ifTier: 'IF≥20' },
];

export const FALLBACK_ENTRIES: PdbEntry[] = ENTRY_TEMPLATES.map(t => ({
  ...t,
  releaseDate: `2025-01-${String(Math.floor(Math.random() * 28) + 1).padStart(2, '0')}`,
  fetchDate: '2025-03-03T00:00:00.000Z',
  pubmedTitle: t.title,
  pubmedAuthors: t.authors,
  pubmedAbstract: `${t.title}. This study presents the ${t.method === 'Cryo-EM' ? 'cryo-electron microscopy' : t.method === 'X-RAY DIFFRACTION' ? 'X-ray crystallographic' : 'solution NMR'} structure of ${t.organisms} protein, providing insights into its molecular mechanism and potential therapeutic applications.`,
}));

// ─── Fallback Evaluations (8) ────────────────────────────────────────────────

const EVAL_STRUCTURES: Record<string, EvalPdbStructure[]> = {
  P04637: [
    { id: 1, uniprotId: 'P04637', pdbId: '8V9A', method: 'Cryo-EM', resolution: 3.2, title: 'Structure of p53 tetramer bound to DNA', depositionDate: '2024-11-15', releaseDate: '2025-01-08', ligand: null, ligandNames: null, journal: 'Nature', journalIf: 64.8, doi: '10.1038/s41586-024-07812-3', pubmedId: '38912345', organism: 'Homo sapiens', authors: 'Zhang Y, Wang L', isCryoem: true, isXray: false, isNmr: false, ifTier: 'IF≥20', chainId: 'A', unpStart: 1, unpEnd: 393 },
  ],
  P00533: [
    { id: 2, uniprotId: 'P00533', pdbId: '9A1P', method: 'X-RAY DIFFRACTION', resolution: 2.4, title: 'EGFR kinase domain with osimertinib', depositionDate: '2024-10-20', releaseDate: '2025-02-18', ligand: 'OSI', ligandNames: 'Osimertinib', journal: 'Cancer Discov.', journalIf: 29.5, doi: '10.1158/2159-8290.CD-24-0123', pubmedId: '38972347', organism: 'Homo sapiens', authors: 'Yun C, Boggon T', isCryoem: false, isXray: true, isNmr: false, ifTier: 'IF≥20', chainId: 'A', unpStart: 696, unpEnd: 1022 },
    { id: 3, uniprotId: 'P00533', pdbId: '9A1D', method: 'X-RAY DIFFRACTION', resolution: 2.1, title: 'EGFR-erlotinib complex', depositionDate: '2024-09-10', releaseDate: '2025-01-06', ligand: 'ERL', ligandNames: 'Erlotinib', journal: 'Cell', journalIf: 64.5, doi: '10.1016/j.cell.2024.06.018', pubmedId: '38912350', organism: 'Homo sapiens', authors: 'Moore R, Baker S', isCryoem: false, isXray: true, isNmr: false, ifTier: 'IF≥20', chainId: 'A', unpStart: 696, unpEnd: 1022 },
  ],
  P42345: [
    { id: 4, uniprotId: 'P42345', pdbId: '8V9U', method: 'Cryo-EM', resolution: 2.5, title: 'mTOR kinase domain', depositionDate: '2024-12-01', releaseDate: '2025-02-10', ligand: 'ATP', ligandNames: 'Adenosine triphosphate', journal: 'Cell', journalIf: 64.5, doi: '10.1016/j.cell.2024.10.002', pubmedId: '38962351', organism: 'Homo sapiens', authors: 'Bhatt D, Dong Y', isCryoem: true, isXray: false, isNmr: false, ifTier: 'IF≥20', chainId: 'A', unpStart: 1375, unpEnd: 2549 },
  ],
  P24941: [
    { id: 5, uniprotId: 'P24941', pdbId: '9A1L', method: 'X-RAY DIFFRACTION', resolution: 2.2, title: 'CDK2-cyclin A with dinaciclib', depositionDate: '2024-11-05', releaseDate: '2025-02-03', ligand: 'DIN', ligandNames: 'Dinaciclib', journal: 'Nat. Commun.', journalIf: 16.6, doi: '10.1038/s41467-024-51234-8', pubmedId: '38952347', organism: 'Homo sapiens', authors: 'Fischer P, End A', isCryoem: false, isXray: true, isNmr: false, ifTier: 'IF≥10', chainId: 'A', unpStart: 1, unpEnd: 298 },
  ],
  Q9Y6K9: [
    { id: 6, uniprotId: 'Q9Y6K9', pdbId: '8V9N', method: 'Cryo-EM', resolution: 2.7, title: 'TRPV1 ion channel structure', depositionDate: '2024-10-15', releaseDate: '2025-02-03', ligand: 'RTX', ligandNames: 'Resiniferatoxin', journal: 'Science', journalIf: 56.9, doi: '10.1126/science.acd1234', pubmedId: '38952349', organism: 'Homo sapiens', authors: 'Liao M, Cao E', isCryoem: true, isXray: false, isNmr: false, ifTier: 'IF≥20', chainId: 'A', unpStart: 1, unpEnd: 839 },
  ],
  P62158: [
    { id: 7, uniprotId: 'P62158', pdbId: '8V9K', method: 'Cryo-EM', resolution: 2.9, title: 'Proteasome 19S regulatory particle', depositionDate: '2024-12-10', releaseDate: '2025-02-17', ligand: 'UBQ', ligandNames: 'Ubiquitin', journal: 'Mol. Cell', journalIf: 16.0, doi: '10.1016/j.molcel.2024.08.003', pubmedId: '38972345', organism: 'Homo sapiens', authors: 'Chen W, Zhao Q', isCryoem: true, isXray: false, isNmr: false, ifTier: 'IF≥10', chainId: 'A', unpStart: 1, unpEnd: 243 },
  ],
  P0DP23: [
    { id: 8, uniprotId: 'P0DP23', pdbId: '8V9M', method: 'Cryo-EM', resolution: 3.4, title: 'GABA-A receptor with diazepam', depositionDate: '2024-11-20', releaseDate: '2025-01-27', ligand: 'DZP', ligandNames: 'Diazepam', journal: 'Nature', journalIf: 64.8, doi: '10.1038/s41586-024-08567-6', pubmedId: '38942349', organism: 'Homo sapiens', authors: 'Phulera S, Zhu H', isCryoem: true, isXray: false, isNmr: false, ifTier: 'IF≥20', chainId: 'A', unpStart: 1, unpEnd: 456 },
  ],
  P28482: [
    { id: 9, uniprotId: 'P28482', pdbId: '9A2I', method: 'X-RAY DIFFRACTION', resolution: 2.2, title: 'CDK4-cyclin D1 with palbociclib', depositionDate: '2024-12-05', releaseDate: '2025-02-03', ligand: '6BI', ligandNames: 'Palbociclib', journal: 'Cancer Discov.', journalIf: 29.5, doi: '10.1158/2159-8290.CD-24-0567', pubmedId: '38952353', organism: 'Homo sapiens', authors: 'Fry D, Harvey P', isCryoem: false, isXray: true, isNmr: false, ifTier: 'IF≥20', chainId: 'A', unpStart: 1, unpEnd: 303 },
  ],
};

const EVAL_BLAST_RESULTS: Record<string, EvalBlastResult[]> = {
  P04637: [
    { id: 100, uniprotId: 'P04637', pdbId: '2OCJ', uniprotRef: null, description: 'p53 DNA-binding domain', identity: 99.5, evalue: '0.0', queryCoverage: 95.2, targetCoverage: 94.8, method: 'X-RAY DIFFRACTION', resolution: 1.7, releaseDate: '2006-10-03', source: 'pdb', taxonomyId: '9606', journal: 'Cell', journalIf: 64.5, ifTier: 'IF≥20', ligand: 'ZN', title: 'Structure of p53 core domain', pubmedId: '17018277', pubmedTitle: 'Structural basis of p53 inactivation', pubmedAuthors: 'Joerger AC, Fersht AR', pubmedAbstract: 'Structure of p53 core domain.', doi: '10.1016/j.cell.2006.09.018' },
  ],
  P00533: [
    { id: 101, uniprotId: 'P00533', pdbId: '2ITX', uniprotRef: null, description: 'EGFR kinase domain', identity: 98.7, evalue: '0.0', queryCoverage: 92.1, targetCoverage: 91.5, method: 'X-RAY DIFFRACTION', resolution: 2.8, releaseDate: '2007-01-16', source: 'pdb', taxonomyId: '9606', journal: 'Cell', journalIf: 64.5, ifTier: 'IF≥20', ligand: 'ANP', title: 'EGFR T790M mutant', pubmedId: '17289580', pubmedTitle: 'EGFR T790M structure', pubmedAuthors: 'Yun CH, Eck MJ', pubmedAbstract: 'Structure of EGFR T790M mutant.', doi: '10.1016/j.cell.2007.01.014' },
  ],
};

export const FALLBACK_EVALUATIONS: Evaluation[] = [
  {
    uniprotId: 'P04637',
    entryName: 'P53_HUMAN',
    proteinName: 'Cellular tumor antigen p53',
    geneNames: 'TP53',
    organism: 'Homo sapiens',
    sequenceLength: 393,
    coverage: 95.2,
    scores: JSON.stringify({ overall: 88, structure: 92, ligand: 78, journal: 95 }),
    report: 'High-confidence target with multiple high-resolution structures available. Key tumor suppressor with extensive structural coverage.',
    provenance: null,
    batchId: 'BATCH-2025-01',
    createdAt: '2025-01-15T10:30:00.000Z',
    updatedAt: '2025-02-01T14:20:00.000Z',
    pdbStructures: EVAL_STRUCTURES['P04637'] || [],
    blastResults: EVAL_BLAST_RESULTS['P04637'] || [],
    _count: { pdbStructures: 1, blastResults: 1 },
  },
  {
    uniprotId: 'P00533',
    entryName: 'EGFR_HUMAN',
    proteinName: 'Epidermal growth factor receptor',
    geneNames: 'EGFR',
    organism: 'Homo sapiens',
    sequenceLength: 1210,
    coverage: 28.5,
    scores: JSON.stringify({ overall: 82, structure: 85, ligand: 90, journal: 72 }),
    report: 'Important drug target with extensive structural coverage of kinase domain. Multiple FDA-approved inhibitors available.',
    provenance: null,
    batchId: 'BATCH-2025-01',
    createdAt: '2025-01-15T10:31:00.000Z',
    updatedAt: '2025-02-05T09:15:00.000Z',
    pdbStructures: EVAL_STRUCTURES['P00533'] || [],
    blastResults: EVAL_BLAST_RESULTS['P00533'] || [],
    _count: { pdbStructures: 2, blastResults: 1 },
  },
  {
    uniprotId: 'P42345',
    entryName: 'MTOR_HUMAN',
    proteinName: 'Serine/threonine-protein kinase mTOR',
    geneNames: 'MTOR, FRAP1',
    organism: 'Homo sapiens',
    sequenceLength: 2549,
    coverage: 42.8,
    scores: JSON.stringify({ overall: 79, structure: 82, ligand: 75, journal: 80 }),
    report: 'Large kinase with Cryo-EM structural coverage of key domains. Critical signaling hub in cancer metabolism.',
    provenance: null,
    batchId: 'BATCH-2025-01',
    createdAt: '2025-01-15T10:32:00.000Z',
    updatedAt: '2025-02-10T11:00:00.000Z',
    pdbStructures: EVAL_STRUCTURES['P42345'] || [],
    blastResults: [],
    _count: { pdbStructures: 1, blastResults: 0 },
  },
  {
    uniprotId: 'P24941',
    entryName: 'CDK2_HUMAN',
    proteinName: 'Cyclin-dependent kinase 2',
    geneNames: 'CDK2',
    organism: 'Homo sapiens',
    sequenceLength: 298,
    coverage: 98.0,
    scores: JSON.stringify({ overall: 91, structure: 95, ligand: 88, journal: 90 }),
    report: 'Well-characterized cell cycle kinase with near-complete structural coverage. Multiple inhibitor complexes available.',
    provenance: null,
    batchId: 'BATCH-2025-01',
    createdAt: '2025-01-15T10:33:00.000Z',
    updatedAt: '2025-02-03T16:45:00.000Z',
    pdbStructures: EVAL_STRUCTURES['P24941'] || [],
    blastResults: [],
    _count: { pdbStructures: 1, blastResults: 0 },
  },
  {
    uniprotId: 'Q9Y6K9',
    entryName: 'TRPV1_HUMAN',
    proteinName: 'Transient receptor potential cation channel subfamily V member 1',
    geneNames: 'TRPV1',
    organism: 'Homo sapiens',
    sequenceLength: 839,
    coverage: 85.3,
    scores: JSON.stringify({ overall: 85, structure: 90, ligand: 82, journal: 84 }),
    report: 'Pain receptor with high-resolution Cryo-EM structures. Important target for analgesic drug development.',
    provenance: null,
    batchId: 'BATCH-2025-02',
    createdAt: '2025-02-01T08:20:00.000Z',
    updatedAt: '2025-02-15T13:30:00.000Z',
    pdbStructures: EVAL_STRUCTURES['Q9Y6K9'] || [],
    blastResults: [],
    _count: { pdbStructures: 1, blastResults: 0 },
  },
  {
    uniprotId: 'P62158',
    entryName: 'PRS10_HUMAN',
    proteinName: '26S proteasome regulatory subunit 10B',
    geneNames: 'PSMC4',
    organism: 'Homo sapiens',
    sequenceLength: 243,
    coverage: 72.4,
    scores: JSON.stringify({ overall: 76, structure: 80, ligand: 65, journal: 82 }),
    report: 'Proteasome subunit with Cryo-EM coverage. Important for protein degradation pathways.',
    provenance: null,
    batchId: 'BATCH-2025-02',
    createdAt: '2025-02-01T08:25:00.000Z',
    updatedAt: '2025-02-18T10:10:00.000Z',
    pdbStructures: EVAL_STRUCTURES['P62158'] || [],
    blastResults: [],
    _count: { pdbStructures: 1, blastResults: 0 },
  },
  {
    uniprotId: 'P0DP23',
    entryName: 'GBRA5_HUMAN',
    proteinName: 'Gamma-aminobutyric acid receptor subunit alpha-5',
    geneNames: 'GABRA5',
    organism: 'Homo sapiens',
    sequenceLength: 456,
    coverage: 65.8,
    scores: JSON.stringify({ overall: 73, structure: 78, ligand: 70, journal: 72 }),
    report: 'GABA receptor subunit with Cryo-EM structure available. Target for neurological therapeutics.',
    provenance: null,
    batchId: 'BATCH-2025-02',
    createdAt: '2025-02-01T08:30:00.000Z',
    updatedAt: '2025-02-20T09:45:00.000Z',
    pdbStructures: EVAL_STRUCTURES['P0DP23'] || [],
    blastResults: [],
    _count: { pdbStructures: 1, blastResults: 0 },
  },
  {
    uniprotId: 'P28482',
    entryName: 'CDK4_HUMAN',
    proteinName: 'Cyclin-dependent kinase 4',
    geneNames: 'CDK4',
    organism: 'Homo sapiens',
    sequenceLength: 303,
    coverage: 90.5,
    scores: JSON.stringify({ overall: 87, structure: 92, ligand: 85, journal: 88 }),
    report: 'Cell cycle kinase with high structural coverage. FDA-approved inhibitor palbociclib available.',
    provenance: null,
    batchId: 'BATCH-2025-02',
    createdAt: '2025-02-01T08:35:00.000Z',
    updatedAt: '2025-02-22T14:20:00.000Z',
    pdbStructures: EVAL_STRUCTURES['P28482'] || [],
    blastResults: [],
    _count: { pdbStructures: 1, blastResults: 0 },
  },
];

// ─── Fallback Literature Stats ───────────────────────────────────────────────

export const FALLBACK_LIT_STATS: LitStats = {
  totalPapers: 156,
  totalReports: 12,
  papersWithIf: 134,
  latestDate: '2025-03-01',
  avgIf: 12.4,
  topJournal: 'Nature',
  methodDistribution: [
    { method: 'Cryo-EM', count: 68 },
    { method: 'X-RAY DIFFRACTION', count: 62 },
    { method: 'SOLUTION NMR', count: 18 },
    { method: 'Other', count: 8 },
  ],
  ifDistribution: [
    { tier: 'IF≥20', count: 28 },
    { tier: 'IF≥10', count: 45 },
    { tier: 'IF≥5', count: 42 },
    { tier: 'IF<5', count: 41 },
  ],
};

// ─── Fallback Literature Papers (20) ─────────────────────────────────────────

const PAPER_PDBS: Record<string, LitPaperPdb[]> = {
  '38912345': [{ pdbId: '8V9A', method: 'Cryo-EM', resolution: 3.2 }],
  '38912346': [{ pdbId: '8V9B', method: 'Cryo-EM', resolution: 2.8 }],
  '38912347': [{ pdbId: '8V9C', method: 'Cryo-EM', resolution: 3.5 }],
  '38922345': [{ pdbId: '8V9D', method: 'Cryo-EM', resolution: 4.1 }, { pdbId: '9A1S', method: 'X-RAY DIFFRACTION', resolution: 2.5 }],
  '38922346': [{ pdbId: '8V9E', method: 'Cryo-EM', resolution: 3.0 }],
  '38932345': [{ pdbId: '8V9F', method: 'Cryo-EM', resolution: 3.8 }],
  '38932346': [{ pdbId: '8V9G', method: 'Cryo-EM', resolution: 2.6 }],
  '38932347': [{ pdbId: '9A1G', method: 'X-RAY DIFFRACTION', resolution: 2.3 }],
  '38942345': [{ pdbId: '8V9H', method: 'Cryo-EM', resolution: 4.5 }],
  '38942349': [{ pdbId: '8V9M', method: 'Cryo-EM', resolution: 3.4 }],
  '38952345': [{ pdbId: '8V9I', method: 'Cryo-EM', resolution: 3.3 }],
  '38952349': [{ pdbId: '8V9N', method: 'Cryo-EM', resolution: 2.7 }],
  '38962345': [{ pdbId: '8V9J', method: 'Cryo-EM', resolution: 3.6 }],
  '38962348': [{ pdbId: '8V9O', method: 'Cryo-EM', resolution: 3.9 }],
  '38972345': [{ pdbId: '8V9K', method: 'Cryo-EM', resolution: 2.9 }],
  '38972348': [{ pdbId: '8V9P', method: 'Cryo-EM', resolution: 3.0 }],
  '38982345': [{ pdbId: '8V9L', method: 'Cryo-EM', resolution: 3.1 }],
  '38982348': [{ pdbId: '8V9Q', method: 'Cryo-EM', resolution: 4.2 }],
  '38912349': [{ pdbId: '9A1C', method: 'X-RAY DIFFRACTION', resolution: 1.8 }],
  '38972347': [{ pdbId: '9A1P', method: 'X-RAY DIFFRACTION', resolution: 2.4 }],
};

export const FALLBACK_LIT_PAPERS: LitPaper[] = [
  {
    pmid: '38912345',
    title: 'Cryo-EM structure of human mTORC1 complex bound to Rag GTPases reveals allosteric regulation mechanism',
    authors: 'Zhang Y, Wang L, Chen H, Liu X, Zhao M',
    journal: 'Nature',
    IF: 64.8,
    pubdate: '2025-01-08',
    abstract: 'The mechanistic target of rapamycin complex 1 (mTORC1) is a central regulator of cell growth that integrates nutrient and growth factor signals. Here we present the cryo-electron microscopy structure of human mTORC1 bound to Rag GTPases at 3.2 Å resolution. Our structure reveals the molecular basis for Rag-mediated recruitment of mTORC1 to the lysosomal surface and provides insights into the allosteric regulation of mTOR kinase activity by Rag GTPases. These findings advance our understanding of how nutrient signals control cell growth through mTORC1.',
    abstractCn: 'mTORC1复合物是细胞生长的核心调控因子，整合营养和生长因子信号。本文报道了人源mTORC1与Rag GTPase结合的冷冻电镜结构，分辨率3.2Å。结构揭示了Rag介导的mTORC1溶酶体定位的分子基础，为理解营养信号如何通过mTORC1调控细胞生长提供了新见解。',
    doi: '10.1038/s41586-024-07812-3',
    pdbs: PAPER_PDBS['38912345'] || [],
    keywords: ['mTOR', 'Cryo-EM', 'Rag GTPase', 'cell growth'],
    tags: ['high-impact', 'cryo-em'],
  },
  {
    pmid: '38912346',
    title: 'Structure of the human spliceosome Bact complex at 2.8 Å resolution reveals catalytic activation mechanism',
    authors: 'Johnson K, Patel R, Singh A, Kumar P',
    journal: 'Science',
    IF: 56.9,
    pubdate: '2025-01-09',
    abstract: 'Pre-mRNA splicing is catalyzed by the spliceosome, a dynamic macromolecular machine. We determined the cryo-EM structure of the human spliceosome Bact complex at 2.8 Å resolution. The structure reveals conformational changes during catalytic activation and provides mechanistic insights into the rearrangement of the catalytic core. Our findings illuminate the molecular basis of spliceosome activation and have implications for understanding splicing-related diseases.',
    abstractCn: '前体mRNA剪接由剪接体催化，这是一个动态的大分子机器。本文报道了人源剪接体Bact复合物2.8Å分辨率的冷冻电镜结构，揭示了催化激活过程中的构象变化，为理解剪接体激活的分子机制提供了新见解。',
    doi: '10.1126/science.adq4567',
    pdbs: PAPER_PDBS['38912346'] || [],
    keywords: ['spliceosome', 'pre-mRNA splicing', 'cryo-EM'],
    tags: ['high-impact'],
  },
  {
    pmid: '38912347',
    title: 'Cryo-EM structure of the yeast ribosome-nascent chain complex reveals co-translational folding intermediates',
    authors: 'Tanaka M, Suzuki K, Yamamoto T, Nakamura H',
    journal: 'Cell',
    IF: 64.5,
    pubdate: '2025-01-10',
    abstract: 'Co-translational protein folding is a fundamental process that ensures proper protein biogenesis. We present the cryo-EM structure of a yeast ribosome-nascent chain complex at 3.5 Å resolution, capturing an intermediate folding state of the nascent polypeptide. The structure reveals how the ribosome exit tunnel influences early folding events and how chaperone interactions stabilize emerging structural elements.',
    abstractCn: '共翻译蛋白折叠是确保蛋白质正确生物发生的基本过程。本文报道了酵母核糖体-新生肽链复合物3.5Å分辨率的冷冻电镜结构，捕获了新生多肽的中间折叠状态，揭示了核糖体出口通道如何影响早期折叠事件。',
    doi: '10.1016/j.cell.2024.07.012',
    pdbs: PAPER_PDBS['38912347'] || [],
    keywords: ['ribosome', 'co-translational folding', 'chaperone'],
    tags: ['cryo-em'],
  },
  {
    pmid: '38922345',
    title: 'Structural basis for broad neutralization of SARS-CoV-2 variants by a potent antibody targeting the receptor-binding domain',
    authors: 'Li X, Wu J, Chen G, Yang F',
    journal: 'Nat. Commun.',
    IF: 16.6,
    pubdate: '2025-01-15',
    abstract: 'The emergence of SARS-CoV-2 variants with immune escape mutations highlights the need for broadly neutralizing antibodies. We report the cryo-EM structure of the Omicron spike protein in complex with a broadly neutralizing antibody at 4.1 Å resolution. The antibody targets a conserved epitope on the receptor-binding domain that is maintained across variants, providing a structural basis for broad neutralization.',
    abstractCn: 'SARS-CoV-2免疫逃逸变异株的出现凸显了广谱中和抗体的需求。本文报道了Omicron刺突蛋白与广谱中和抗体复合物4.1Å分辨率的冷冻电镜结构，抗体靶向受体结合域上的保守表位，为广谱中和提供了结构基础。',
    doi: '10.1038/s41467-024-50123-4',
    pdbs: PAPER_PDBS['38922345'] || [],
    keywords: ['SARS-CoV-2', 'antibody', 'spike protein'],
    tags: ['covid-19', 'therapeutic'],
  },
  {
    pmid: '38922346',
    title: 'Cryo-EM structure of the human BK channel in lipid nanodisc reveals lipid-mediated gating regulation',
    authors: 'Kim S, Park J, Lee Y, Choi H',
    journal: 'Nat. Struct. Mol. Biol.',
    IF: 16.8,
    pubdate: '2025-01-16',
    abstract: 'Large-conductance calcium-activated potassium (BK) channels are essential for neuronal excitability and vascular tone. We determined the cryo-EM structure of the human BK channel reconstituted in lipid nanodiscs at 3.0 Å resolution. The structure reveals lipid interactions at the transmembrane domain that modulate channel gating, providing new insights into the lipid-dependent regulation of BK channels.',
    abstractCn: '大电导钙激活钾(BK)通道对神经元兴奋性和血管张力至关重要。本文报道了脂质纳米盘中重组人BK通道3.0Å分辨率的冷冻电镜结构，揭示了跨膜结构域的脂质相互作用调控通道门控的新机制。',
    doi: '10.1038/s41594-024-01345-2',
    pdbs: PAPER_PDBS['38922346'] || [],
    keywords: ['BK channel', 'ion channel', 'lipid regulation'],
    tags: ['ion-channel'],
  },
  {
    pmid: '38932345',
    title: 'Structure of the Thermus thermophilus 70S ribosome reveals tRNA dynamics during translocation',
    authors: 'Ivanov A, Petrov B, Sokolova E, Morozov D',
    journal: 'PNAS',
    IF: 11.1,
    pubdate: '2025-01-22',
    abstract: 'Ribosomal translocation is a key step in protein synthesis. We present the cryo-EM structure of the Thermus thermophilus 70S ribosome with tRNA at 3.8 Å resolution, capturing an intermediate state of translocation. The structure reveals the coordinated movement of tRNA and mRNA through the ribosome, providing mechanistic insights into this fundamental process.',
    abstractCn: '核糖体易位是蛋白质合成的关键步骤。本文报道了嗜热栖热菌70S核糖体与tRNA复合物3.8Å分辨率的冷冻电镜结构，捕获了易位的中间状态，揭示了tRNA和mRNA在核糖体中的协调运动。',
    doi: '10.1073/pnas.2401234567',
    pdbs: PAPER_PDBS['38932345'] || [],
    keywords: ['ribosome', 'translocation', 'tRNA'],
    tags: ['translation'],
  },
  {
    pmid: '38932346',
    title: 'High-resolution cryo-EM structure of human mitochondrial ATP synthase reveals rotary catalysis mechanism',
    authors: 'Murphy B, Brown D, Wilson E, Taylor S',
    journal: 'Nature',
    IF: 64.8,
    pubdate: '2025-01-23',
    abstract: 'Mitochondrial ATP synthase is the molecular machine that produces cellular energy. We determined the cryo-EM structure of human mitochondrial ATP synthase at 2.6 Å resolution, revealing detailed interactions in the rotary catalytic mechanism. The structure provides insights into proton-driven rotation and ATP synthesis, advancing our understanding of bioenergetics.',
    abstractCn: '线粒体ATP合酶是产生细胞能量的分子机器。本文报道了人源线粒体ATP合酶2.6Å分辨率的冷冻电镜结构，揭示了旋转催化机制中的详细相互作用，为理解质子驱动旋转和ATP合成提供了新见解。',
    doi: '10.1038/s41586-024-08012-7',
    pdbs: PAPER_PDBS['38932346'] || [],
    keywords: ['ATP synthase', 'mitochondria', 'bioenergetics'],
    tags: ['high-impact', 'metabolism'],
  },
  {
    pmid: '38932347',
    title: 'Crystal structure of the Arabidopsis thaliana auxin receptor TIR1 reveals auxin perception mechanism',
    authors: 'Tanabe S, Nagata K, Onishi M, Fujita H',
    journal: 'Nature',
    IF: 64.8,
    pubdate: '2025-01-24',
    abstract: 'Auxin is a key plant hormone regulating growth and development. We determined the crystal structure of the Arabidopsis thaliana auxin receptor TIR1 at 2.3 Å resolution. The structure reveals the molecular basis of auxin perception and provides a framework for understanding how auxin controls diverse developmental processes in plants.',
    abstractCn: '生长素是调控植物生长发育的关键激素。本文报道了拟南芥生长素受体TIR1的2.3Å分辨率晶体结构，揭示了生长素感知的分子基础，为理解生长素如何调控植物发育提供了框架。',
    doi: '10.1038/s41586-024-08345-3',
    pdbs: PAPER_PDBS['38932347'] || [],
    keywords: ['auxin', 'plant hormone', 'TIR1'],
    tags: ['plant-biology'],
  },
  {
    pmid: '38942345',
    title: 'Structure of the ER translocon-Sec61 complex with ribosome reveals protein translocation mechanism',
    authors: 'Andersen C, Nielsen P, Jensen K, Larsen M',
    journal: 'eLife',
    IF: 7.7,
    pubdate: '2025-01-29',
    abstract: 'Protein translocation across the endoplasmic reticulum membrane is mediated by the Sec61 translocon. We present the cryo-EM structure of the ribosome-Sec61 complex at 4.5 Å resolution, capturing the translocation intermediate. The structure reveals how the ribosome positions the nascent chain at the translocon and how Sec61 facilitates membrane insertion.',
    abstractCn: '蛋白质在内质网膜上的易位由Sec61转位子介导。本文报道了核糖体-Sec61复合物4.5Å分辨率的冷冻电镜结构，捕获了易位中间体，揭示了核糖体如何将新生肽链定位到转位子以及Sec61如何促进膜插入。',
    doi: '10.7554/eLife.92345',
    pdbs: PAPER_PDBS['38942345'] || [],
    keywords: ['Sec61', 'translocon', 'ER'],
    tags: ['protein-transport'],
  },
  {
    pmid: '38942349',
    title: 'Structure of the human GABA-A receptor in complex with diazepam reveals benzodiazepine mechanism of action',
    authors: 'Phulera S, Zhu H, Yu J, Bhatt D',
    journal: 'Nature',
    IF: 64.8,
    pubdate: '2025-01-30',
    abstract: 'GABA-A receptors are the primary inhibitory neurotransmitter receptors in the brain and targets of benzodiazepines. We determined the cryo-EM structure of the human GABA-A receptor bound to diazepam at 3.4 Å resolution. The structure reveals the benzodiazepine binding site and allosteric mechanism, providing a basis for designing improved anxiolytics.',
    abstractCn: 'GABA-A受体是大脑中主要的抑制性神经递质受体，也是苯二氮卓类药物的靶点。本文报道了人GABA-A受体与地西泮结合的3.4Å分辨率冷冻电镜结构，揭示了苯二氮卓类药物的结合位点和变构机制。',
    doi: '10.1038/s41586-024-08567-6',
    pdbs: PAPER_PDBS['38942349'] || [],
    keywords: ['GABA-A', 'diazepam', 'neurotransmitter'],
    tags: ['high-impact', 'neurology'],
  },
  {
    pmid: '38952345',
    title: 'Structure of human TFIIH transcription factor complex reveals DNA opening mechanism',
    authors: 'Garcia R, Martinez L, Lopez F, Torres J',
    journal: 'Science',
    IF: 56.9,
    pubdate: '2025-02-05',
    abstract: 'TFIIH is a general transcription factor essential for RNA polymerase II transcription initiation. We present the cryo-EM structure of human TFIIH at 3.3 Å resolution, revealing the architecture of the core complex and the mechanism of DNA opening during transcription initiation.',
    abstractCn: 'TFIIH是RNA聚合酶II转录起始所必需的通用转录因子。本文报道了人源TFIIH 3.3Å分辨率的冷冻电镜结构，揭示了核心复合物的结构和转录起始期间DNA打开的机制。',
    doi: '10.1126/science.abq5678',
    pdbs: PAPER_PDBS['38952345'] || [],
    keywords: ['TFIIH', 'transcription', 'DNA opening'],
    tags: ['high-impact', 'gene-expression'],
  },
  {
    pmid: '38952349',
    title: 'Cryo-EM structure of the human TRPV1 ion channel reveals vanilloid binding and activation mechanism',
    authors: 'Liao M, Cao E, Julius D, Cheng Y',
    journal: 'Science',
    IF: 56.9,
    pubdate: '2025-02-06',
    abstract: 'TRPV1 is a heat-activated ion channel that serves as the receptor for capsaicin. We determined the cryo-EM structure of human TRPV1 at 2.7 Å resolution, revealing the vanilloid binding site and the conformational changes associated with channel activation. These findings advance our understanding of pain signaling and provide a foundation for analgesic drug design.',
    abstractCn: 'TRPV1是热激活离子通道，也是辣椒素的受体。本文报道了人源TRPV1 2.7Å分辨率的冷冻电镜结构，揭示了香草醛结合位点和通道激活相关的构象变化，为疼痛信号传导研究和镇痛药物设计提供了基础。',
    doi: '10.1126/science.acd1234',
    pdbs: PAPER_PDBS['38952349'] || [],
    keywords: ['TRPV1', 'capsaicin', 'pain'],
    tags: ['high-impact', 'ion-channel'],
  },
  {
    pmid: '38962345',
    title: 'Cryo-EM structure of the Anopheles gambiae odorant receptor reveals insect olfaction mechanism',
    authors: 'Omondi O, Mwangi P, Kiptoo K, Rotich J',
    journal: 'Nature',
    IF: 64.8,
    pubdate: '2025-02-12',
    abstract: 'Insect odorant receptors are key targets for vector control strategies. We present the cryo-EM structure of the Anopheles gambiae odorant receptor at 3.6 Å resolution, revealing the ligand-binding pocket and activation mechanism. These insights could inform the development of novel mosquito repellents.',
    abstractCn: '昆虫气味受体是媒介控制策略的关键靶点。本文报道了冈比亚按蚊气味受体3.6Å分辨率的冷冻电镜结构，揭示了配体结合口袋和激活机制，可为新型驱蚊剂的研发提供指导。',
    doi: '10.1038/s41586-024-08234-5',
    pdbs: PAPER_PDBS['38962345'] || [],
    keywords: ['odorant receptor', 'mosquito', 'olfaction'],
    tags: ['high-impact', 'vector-control'],
  },
  {
    pmid: '38962348',
    title: 'Cryo-EM structure of the Plasmodium falciparum 80S ribosome reveals antimalarial drug target sites',
    authors: 'Wong W, Bai X, Barcina I, Bhatt D',
    journal: 'Nat. Struct. Mol. Biol.',
    IF: 16.8,
    pubdate: '2025-02-13',
    abstract: 'Malaria remains a major global health challenge. We determined the cryo-EM structure of the Plasmodium falciparum 80S ribosome at 3.9 Å resolution. The structure reveals unique features of the parasite ribosome that could be exploited for antimalarial drug development.',
    abstractCn: '疟疾仍是全球重大健康挑战。本文报道了恶性疟原虫80S核糖体3.9Å分辨率的冷冻电镜结构，揭示了寄生虫核糖体的独特特征，可用于抗疟药物开发。',
    doi: '10.1038/s41594-024-01567-9',
    pdbs: PAPER_PDBS['38962348'] || [],
    keywords: ['Plasmodium', 'ribosome', 'malaria'],
    tags: ['antimalarial'],
  },
  {
    pmid: '38972345',
    title: 'Cryo-EM structure of the human proteasome 19S regulatory particle reveals substrate recognition mechanism',
    authors: 'Chen W, Zhao Q, Sun H, Zhou J',
    journal: 'Mol. Cell',
    IF: 16.0,
    pubdate: '2025-02-19',
    abstract: 'The 26S proteasome degrades ubiquitinated proteins in eukaryotic cells. We present the cryo-EM structure of the human 19S regulatory particle at 2.9 Å resolution, revealing how ubiquitin receptors recognize polyubiquitinated substrates and initiate protein degradation.',
    abstractCn: '26S蛋白酶体降解真核细胞中的泛素化蛋白质。本文报道了人源19S调节颗粒2.9Å分辨率的冷冻电镜结构，揭示了泛素受体如何识别多泛素化底物并启动蛋白质降解。',
    doi: '10.1016/j.molcel.2024.08.003',
    pdbs: PAPER_PDBS['38972345'] || [],
    keywords: ['proteasome', 'ubiquitin', 'protein degradation'],
    tags: ['protein-quality'],
  },
  {
    pmid: '38972347',
    title: 'Crystal structure of the human EGFR kinase domain with osimertinib reveals resistance mutation mechanism',
    authors: 'Yun C, Boggon T, Li Y, Eck M',
    journal: 'Cancer Discov.',
    IF: 29.5,
    pubdate: '2025-02-20',
    abstract: 'EGFR T790M mutation confers resistance to first-generation EGFR inhibitors. We determined the crystal structure of EGFR kinase domain bound to osimertinib at 2.4 Å resolution. The structure reveals how osimertinib overcomes T790M-mediated resistance and provides insights into the design of next-generation inhibitors.',
    abstractCn: 'EGFR T790M突变导致对第一代EGFR抑制剂的耐药性。本文报道了EGFR激酶结构域与奥希替尼结合的2.4Å分辨率晶体结构，揭示了奥希替尼如何克服T790M介导的耐药性，并为下一代抑制剂的设计提供了见解。',
    doi: '10.1158/2159-8290.CD-24-0123',
    pdbs: PAPER_PDBS['38972347'] || [],
    keywords: ['EGFR', 'osimertinib', 'drug resistance'],
    tags: ['cancer', 'drug-resistance'],
  },
  {
    pmid: '38972348',
    title: 'Structure of the human PIEZO1 mechanosensitive ion channel reveals force-sensing mechanism',
    authors: 'Zhao Q, Zhou H, Chi S, Wang Y',
    journal: 'Cell',
    IF: 64.5,
    pubdate: '2025-02-21',
    abstract: 'PIEZO1 is a mechanosensitive ion channel essential for various physiological processes. We present the cryo-EM structure of human PIEZO1 at 3.0 Å resolution. The structure reveals the force-sensing blade domains and the ion-conducting pore, providing a mechanistic understanding of mechanotransduction.',
    abstractCn: 'PIEZO1是多种生理过程不可或缺的机械敏感离子通道。本文报道了人源PIEZO1 3.0Å分辨率的冷冻电镜结构，揭示了力传感叶片结构域和离子传导孔，为机械转导提供了机制理解。',
    doi: '10.1016/j.cell.2024.09.003',
    pdbs: PAPER_PDBS['38972348'] || [],
    keywords: ['PIEZO1', 'mechanosensation', 'ion channel'],
    tags: ['high-impact', 'mechanobiology'],
  },
  {
    pmid: '38982345',
    title: 'NMR structure of the E. coli RNA polymerase elongation complex reveals transcription fidelity mechanism',
    authors: 'Shapiro N, Cohen R, Levy T, Avraham D',
    journal: 'Nucleic Acids Res.',
    IF: 16.7,
    pubdate: '2025-02-26',
    abstract: 'RNA polymerase elongation complexes maintain transcription fidelity through nucleotide selection. We present the cryo-EM structure of the E. coli RNA polymerase elongation complex at 3.1 Å resolution, revealing the structural basis for nucleotide selection and proofreading during transcription elongation.',
    abstractCn: 'RNA聚合酶延伸复合物通过核苷酸选择维持转录保真度。本文报道了大肠杆菌RNA聚合酶延伸复合物3.1Å分辨率的冷冻电镜结构，揭示了转录延伸过程中核苷酸选择和校读的结构基础。',
    doi: '10.1093/nar/gkae567',
    pdbs: PAPER_PDBS['38982345'] || [],
    keywords: ['RNA polymerase', 'transcription', 'fidelity'],
    tags: ['gene-expression'],
  },
  {
    pmid: '38982348',
    title: 'Structure of the Vibrio cholerae type VI secretion system reveals bacteriolytic mechanism',
    authors: 'Basler M, Pilhofer M, Bhatt D, Bhatt A',
    journal: 'Nat. Microbiol.',
    IF: 28.3,
    pubdate: '2025-02-27',
    abstract: 'The type VI secretion system (T6SS) is a bacterial nanomachine that delivers effectors to neighboring cells. We determined the cryo-EM structure of the Vibrio cholerae T6SS at 4.2 Å resolution, revealing the contractile sheath-tube mechanism and effector loading strategy.',
    abstractCn: 'VI型分泌系统(T6SS)是一种将效应蛋白递送至邻近细胞的细菌纳米机器。本文报道了霍乱弧菌T6SS 4.2Å分辨率的冷冻电镜结构，揭示了收缩鞘-管机制和效应蛋白装载策略。',
    doi: '10.1038/s41564-024-01789-3',
    pdbs: PAPER_PDBS['38982348'] || [],
    keywords: ['T6SS', 'secretion system', 'bacteriolysis'],
    tags: ['microbiology'],
  },
  {
    pmid: '38912349',
    title: 'Crystal structure of the SARS-CoV-2 main protease with nirmatrelvir reveals inhibition mechanism',
    authors: 'Wang Z, Liu Q, Sun W, Zhang F',
    journal: 'Nature',
    IF: 64.8,
    pubdate: '2025-01-08',
    abstract: 'The SARS-CoV-2 main protease (Mpro) is the target of the antiviral drug nirmatrelvir. We determined the crystal structure of Mpro bound to nirmatrelvir at 1.8 Å resolution. The structure reveals the covalent inhibition mechanism and provides a basis for designing next-generation Mpro inhibitors with improved potency.',
    abstractCn: 'SARS-CoV-2主蛋白酶(Mpro)是抗病毒药物奈玛特韦的靶点。本文报道了Mpro与奈玛特韦结合的1.8Å分辨率晶体结构，揭示了共价抑制机制，为设计具有更高活性的下一代Mpro抑制剂提供了基础。',
    doi: '10.1038/s41586-024-07923-1',
    pdbs: PAPER_PDBS['38912349'] || [],
    keywords: ['Mpro', 'nirmatrelvir', 'SARS-CoV-2'],
    tags: ['high-impact', 'covid-19'],
  },
];

// ─── Fallback Literature Reports (5) ─────────────────────────────────────────

export const FALLBACK_LIT_REPORTS: LitReport[] = [
  {
    id: 1,
    date: '2025-01-13',
    paperCount: 8,
    createdAt: '2025-01-13T08:00:00.000Z',
    title: 'Weekly Literature Report - W02',
    summary: 'Eight new structural biology papers published this week, including high-impact Cryo-EM studies of mTORC1 and the spliceosome from Nature and Science respectively. Notable advances in understanding large macromolecular complexes.',
  },
  {
    id: 2,
    date: '2025-01-20',
    paperCount: 7,
    createdAt: '2025-01-20T08:00:00.000Z',
    title: 'Weekly Literature Report - W03',
    summary: 'Seven papers this week featuring structures of the mitochondrial ATP synthase at high resolution and the auxin receptor TIR1. Plant biology and bioenergetics highlight this week\'s report.',
  },
  {
    id: 3,
    date: '2025-02-03',
    paperCount: 6,
    createdAt: '2025-02-03T08:00:00.000Z',
    title: 'Weekly Literature Report - W05',
    summary: 'Six papers this week including breakthrough structures of TFIIH and TRPV1. Ion channel structural biology continues to be a dominant theme in high-impact publications.',
  },
  {
    id: 4,
    date: '2025-02-17',
    paperCount: 5,
    createdAt: '2025-02-17T08:00:00.000Z',
    title: 'Weekly Literature Report - W07',
    summary: 'Five papers this week with notable structures of the PIEZO1 mechanosensor and EGFR with osimertinib. Cancer biology and mechanobiology are prominent themes.',
  },
  {
    id: 5,
    date: '2025-02-24',
    paperCount: 4,
    createdAt: '2025-02-24T08:00:00.000Z',
    title: 'Weekly Literature Report - W08',
    summary: 'Four papers this week including the Vibrio cholerae T6SS structure and E. coli RNA polymerase elongation complex. Bacterial structural biology highlights this week.',
  },
];

// ─── Fallback Weekly Reports ─────────────────────────────────────────────────

export const FALLBACK_REPORTS: WeeklyReport[] = [
  {
    id: 1,
    weekId: 'W01',
    reportType: 'weekly_summary',
    title: 'Weekly Summary - W01 (Jan 6-12, 2025)',
    content: '# Weekly Summary W01\n\n312 structures released this week.\n\n## Highlights\n- Cryo-EM structure of mTORC1 at 3.2 Å (Nature)\n- Spliceosome Bact complex at 2.8 Å (Science)\n- Yeast ribosome-nascent chain complex (Cell)\n\n## Method Distribution\n- X-ray: 198 structures (63.5%)\n- Cryo-EM: 89 structures (28.5%)\n- NMR: 22 structures (7.1%)\n- Other: 3 structures (1.0%)\n\n## Notable Journals\n- Nature: 5 structures\n- Science: 3 structures\n- Cell: 4 structures',
    filename: 'W01_summary.md',
    createdAt: '2025-01-13T00:00:00.000Z',
  },
  {
    id: 2,
    weekId: 'W02',
    reportType: 'weekly_summary',
    title: 'Weekly Summary - W02 (Jan 13-19, 2025)',
    content: '# Weekly Summary W02\n\n287 structures released this week.\n\n## Highlights\n- SARS-CoV-2 Omicron spike protein structure (Nat. Commun.)\n- Human BK channel in lipid nanodisc (Nat. Struct. Mol. Biol.)\n\n## Method Distribution\n- X-ray: 175 structures (61.0%)\n- Cryo-EM: 82 structures (28.6%)\n- NMR: 25 structures (8.7%)\n- Other: 5 structures (1.7%)',
    filename: 'W02_summary.md',
    createdAt: '2025-01-20T00:00:00.000Z',
  },
  {
    id: 3,
    weekId: 'W03',
    reportType: 'weekly_summary',
    title: 'Weekly Summary - W03 (Jan 20-26, 2025)',
    content: '# Weekly Summary W03\n\n345 structures released this week.\n\n## Highlights\n- High-resolution mTORC1 structure at 2.6 Å (Nature)\n- Auxin receptor TIR1 crystal structure (Nature)\n- M. tuberculosis InhA inhibitor complex\n\n## Method Distribution\n- X-ray: 210 structures (60.9%)\n- Cryo-EM: 98 structures (28.4%)\n- NMR: 30 structures (8.7%)\n- Other: 7 structures (2.0%)',
    filename: 'W03_summary.md',
    createdAt: '2025-01-27T00:00:00.000Z',
  },
  {
    id: 4,
    weekId: 'W05',
    reportType: 'weekly_summary',
    title: 'Weekly Summary - W05 (Feb 3-9, 2025)',
    content: '# Weekly Summary W05\n\n330 structures released this week.\n\n## Highlights\n- TFIIH transcription factor complex (Science)\n- TRPV1 ion channel at 2.7 Å (Science)\n- CDK2-cyclin A with dinaciclib (Nat. Commun.)\n\n## Method Distribution\n- X-ray: 195 structures (59.1%)\n- Cryo-EM: 102 structures (30.9%)\n- NMR: 26 structures (7.9%)\n- Other: 7 structures (2.1%)',
    filename: 'W05_summary.md',
    createdAt: '2025-02-10T00:00:00.000Z',
  },
  {
    id: 5,
    weekId: 'W07',
    reportType: 'weekly_summary',
    title: 'Weekly Summary - W07 (Feb 17-23, 2025)',
    content: '# Weekly Summary W07\n\n356 structures released this week — highest count this quarter.\n\n## Highlights\n- PIEZO1 mechanosensitive channel (Cell)\n- EGFR-osimertinib resistance structure (Cancer Discov.)\n- Proteasome 19S regulatory particle (Mol. Cell)\n\n## Method Distribution\n- X-ray: 215 structures (60.4%)\n- Cryo-EM: 105 structures (29.5%)\n- NMR: 28 structures (7.9%)\n- Other: 8 structures (2.2%)',
    filename: 'W07_summary.md',
    createdAt: '2025-02-24T00:00:00.000Z',
  },
  {
    id: 6,
    weekId: 'W08',
    reportType: 'weekly_summary',
    title: 'Weekly Summary - W08 (Feb 24-Mar 2, 2025)',
    content: '# Weekly Summary W08\n\n320 structures released this week.\n\n## Highlights\n- V. cholerae T6SS structure (Nat. Microbiol.)\n- E. coli RNA polymerase elongation complex (Nucleic Acids Res.)\n- NLRP3 inflammasome ring complex (Nature)\n\n## Method Distribution\n- X-ray: 190 structures (59.4%)\n- Cryo-EM: 95 structures (29.7%)\n- NMR: 27 structures (8.4%)\n- Other: 8 structures (2.5%)',
    filename: 'W08_summary.md',
    createdAt: '2025-03-03T00:00:00.000Z',
  },
];
