/**
 * Journal Impact Factor mapping table
 * 
 * Maps normalized PubMed journal names to their 2024 impact factors.
 * Sources: Wikipedia, Journal Citation Reports
 * This is used as a fallback when:
 * 1. The journal is not found in PdbStructure table
 * 2. The journal name doesn't match any PdbStructure journal via alias or n-gram
 */

// Map of normalized journal name → impact factor
// Keys are pre-normalized via normJournal(): lowercase, stripped of spaces/punctuation
const normJournal = (s: string): string => s.toLowerCase().replace(/[\s.&,\-.:;()\[\]{}]/g, '');

// Raw mapping: journal name (any format) → IF
// Will be auto-normalized at module load time
const JOURNAL_IF_MAP_RAW: Record<string, number> = {
  // === Nature family (from Wikipedia 2024 JCR) ===
  'nature': 64.8,  // from PdbStructure
  'nature structural & molecular biology': 16.1,  // from PdbStructure
  'nature structural &amp; molecular biology': 16.1,
  'nature structural and molecular biology': 16.1,
  'nature communications': 17.7,  // from PdbStructure
  'nature methods': 36.1,
  'nature biotechnology': 33.1,
  'nature cell biology': 21.3,
  'nature chemical biology': 13.5,
  'nat chem biol': 13.5,
  'natchembiol': 13.5,
  'nature genetics': 31.7,
  'nature immunology': 25.6,
  'nature medicine': 58.7,
  'nature neuroscience': 25.0,
  'nature physics': 19.6,
  'nature chemistry': 20.8,
  'nature photonics': 32.9,
  'nature nanotechnology': 38.3,
  'nature energy': 56.7,
  'nature catalysis': 33.6,
  'nature machine intelligence': 25.9,
  'nature computational science': 12.0,
  'nature human behaviour': 29.9,
  'nature food': 23.6,
  'nature metabolism': 20.8,
  'nature sustainability': 19.1,
  'nature water': 14.2,
  'nature climate change': 25.8,
  'nature geoscience': 18.3,
  'nature astronomy': 12.0,
  'nature ecology & evolution': 16.8,
  'nature reviews molecular cell biology': 113.9,
  'nature reviews drug discovery': 120.1,
  'nature reviews cancer': 68.8,
  'nature reviews immunology': 100.7,
  'nature reviews microbiology': 78.3,
  'nature reviews genetics': 42.7,
  'nature reviews clinical oncology': 78.8,
  'nature reviews cardiology': 49.6,
  'nature reviews gastroenterology & hepatology': 65.1,
  'nature reviews neurology': 38.1,
  'nature reviews urology': 16.4,
  'nature reviews rheumatology': 33.7,
  'nature reviews endocrinology': 38.0,
  'nature reviews nephrology': 20.7,
  'nature reviews materials': 79.8,
  'nature reviews chemistry': 38.1,
  'nature reviews physics': 34.9,
  'nature reviews earth & environment': 37.2,
  'nature reviews methods primers': 46.2,
  'nature reviews disease primers': 59.9,
  'nature biomedical engineering': 28.1,
  // === Cell family ===
  'cell': 66.9,  // from PdbStructure
  'cell research': 44.1,  // from PdbStructure
  'cell res.': 44.1,
  'cell reports': 7.5,  // from PdbStructure
  'cell reports medicine': 14.3,
  'cell stem cell': 23.9,
  'cell host & microbe': 30.3,  // from PdbStructure
  'cell host and microbe': 30.3,
  'cell discovery': 12.0,  // from PdbStructure
  'cell metabolism': 29.0,
  'cell chemical biology': 7.2,
  'cell systems': 9.3,
  'cell reports physical sciences': 7.9,
  'cell communication and signaling': 8.0,
  'cell commun signal': 8.0,
  'cell cycle': 5.0,
  'cell cycle (georgetown, tex.)': 5.0,
  'cellular & molecular biology letters': 3.5,
  'cellular and molecular biology letters': 3.5,
  // === Science family ===
  'science': 56.9,  // from PdbStructure
  'science (new york, n.y.)': 56.9,
  'science advances': 14.1,  // from PdbStructure
  'science translational medicine': 14.6,
  'science immunology': 16.1,
  'science robotics': 25.0,
  'science signaling': 6.7,
  // === EMBO ===
  'embo journal': 8.3,  // from PdbStructure
  'embo j.': 8.3,
  'embo reports': 7.8,
  // === PNAS ===
  'proc natl acad sci usa': 11.1,  // from PdbStructure
  'pnas': 11.1,
  'proceedings of the national academy of sciences': 11.1,
  'proceedings of the national academy of sciences of the united states of america': 11.1,
  'pnas nexus': 3.0,
  // === ACS journals ===
  'j am chem soc': 15.0,  // from PdbStructure
  'journal of the american chemical society': 15.0,
  'jacs au': 15.0,
  'acs chemical biology': 5.5,  // from PdbStructure
  'acs chem biol': 5.5,
  'acs catalysis': 13.1,  // from PdbStructure
  'acs central science': 18.0,
  'acs medicinal chemistry letters': 4.0,
  'acs infectious diseases': 5.0,
  'acs sensors': 8.2,
  'acs applied materials & interfaces': 8.5,
  'acs macro letters': 5.1,
  'acs sustainable chemistry & engineering': 7.3,
  'acs omega': 3.5,
  'acs pharmacology & translational science': 5.0,
  'acs bio med chem au': 4.0,
  'acs chemical neuroscience': 4.0,
  // === Wiley/RSC ===
  'angew chem int ed engl': 16.6,  // from PdbStructure
  'angewandte chemie international edition': 16.6,
  'angewandte chemie (international ed. in english)': 16.6,
  'chembiochem': 2.4,  // from PdbStructure
  'chembiochem : a european journal of chemical biology': 2.4,
  'chemmedchem': 3.5,
  'chemphyschem': 2.9,
  'chemphyschem : a european journal of chemical physics and physical chemistry': 2.9,
  'chem commun (camb)': 4.3,
  'chemical communications (cambridge, england)': 4.3,
  'chem commun': 4.3,
  'chemistry - a european journal': 4.0,
  'chemistry': 4.0,
  'chemistry & biology': 7.2,
  'chemistry and biology': 7.2,
  'chemistry &amp; biology': 7.2,
  'chemrxiv': 0.1,  // from PdbStructure
  // === Elsevier ===
  'current opinion in cell biology': 5.0,
  'current opinion in biotechnology': 8.0,
  'current opinion in chemical biology': 5.0,
  'current opinion in microbiology': 5.0,
  'current opinion in immunology': 5.0,
  'current opinion in genetics & development': 5.0,
  'current opinion in neurobiology': 5.0,
  'current opinion in structural biology': 6.0,
  'structure': 4.4,  // from PdbStructure
  'structure (london, england : 1993)': 4.4,
  'structure (london, england 1993)': 4.4,
  'struct dyn': 3.0,
  'journal of molecular biology': 5.6,  // from PdbStructure
  'j mol biol': 5.6,
  'j struct biol': 3.0,
  'journal of biological chemistry': 4.5,  // from PdbStructure
  'j biol chem': 4.5,
  'j. biol. chem.': 4.5,
  'the journal of biological chemistry': 4.5,
  'journal of medicinal chemistry': 7.3,  // from PdbStructure
  'j med chem': 7.3,
  'j. med. chem.': 7.3,
  'european journal of medicinal chemistry': 7.3,  // from PdbStructure
  'eur j med chem': 7.3,
  'eur. j. med. chem.': 7.3,
  'european journal of pharmacology': 5.0,
  'eur j pharmacol': 5.0,
  'eur. j. pharmacol.': 5.0,
  'international journal of biological macromolecules': 8.2,  // from PdbStructure
  'int j biol macromol': 8.2,
  'int. j. biol. macromol.': 8.2,
  'international journal of molecular sciences': 4.9,
  'international journal of pharmaceutics': 5.3,
  'journal of controlled release': 10.8,
  'j control release': 10.8,
  'journal of ethnopharmacology': 5.4,
  'j ethnopharmacol': 5.4,
  'journal of agricultural and food chemistry': 5.7,
  'j agric food chem': 5.7,
  'journal of biochemistry': 3.5,
  'j biochem': 3.5,
  'journal of enzyme inhibition and medicinal chemistry': 5.0,
  'journal of computer-aided molecular design': 4.0,
  'journal of chemical information and modeling': 5.6,
  'journal of chemical theory and computation': 5.5,
  'journal of cheminformatics': 4.5,
  'journal of computational chemistry': 3.5,
  'journal of molecular modeling': 2.5,
  'journal of nanobiotechnology': 10.0,
  'journal of magnetic resonance (san diego, calif. : 1997)': 3.0,
  'journal of biomolecular nmr': 3.5,
  'journal of virology': 5.0,
  'journal of bacteriology': 3.5,
  'journal of clinical microbiology': 6.0,
  'journal of neurochemistry': 4.0,
  'journal of neuroscience': 4.0,
  'journal of physiology': 4.0,
  'journal of general physiology': 4.0,
  'journal of membrane biology': 3.5,
  'journal of organic chemistry': 4.0,
  'journal of physical chemistry letters': 5.0,
  'j phys chem lett': 5.0,
  'the journal of physical chemistry letters': 5.0,
  'journal of proteome research': 4.5,
  'journal of visualized experiments': 1.5,
  'biochemical and biophysical research communications': 3.5,
  'biochem biophys res commun': 3.5,
  'biochemical society transactions': 4.0,
  'biochemical journal': 3.7,  // from PdbStructure
  'biochem j': 3.7,
  'biochem. j.': 3.7,
  'british journal of pharmacology': 7.3,  // from PdbStructure
  'br j pharmacol': 7.3,
  'br. j. pharmacol.': 7.3,
  'european journal of organic chemistry': 2.5,
  'febs journal': 5.5,  // from PdbStructure
  'febs j': 5.5,
  'febs j.': 5.5,
  'febs letters': 4.0,
  'febs lett': 4.0,
  'archives of biochemistry and biophysics': 3.0,
  'arch. biochem. biophys.': 3.0,
  'archives of microbiology': 2.5,
  'arch. microbiol.': 2.5,
  'archives of pharmacal research': 3.5,
  'arch. pharmacal res.': 3.5,
  'applied biochemistry and biotechnology': 3.0,
  'appl microbiol biotechnol': 3.0,
  'biotechnology and bioengineering': 3.5,
  'bioresource technology': 11.0,
  'biosensors & bioelectronics': 12.5,
  'biophysical journal': 3.8,
  'biomedicine & pharmacotherapy = biomedecine & pharmacotherapie': 6.5,
  'biomedicine & pharmacotherapy': 6.5,
  'bulletin of mathematical biology': 2.0,
  'canadian journal of physiology and pharmacology': 2.5,
  'computational biology and chemistry': 3.0,
  'clinical and experimental allergy': 5.0,
  'clin exp allergy': 5.0,
  'clinical epigenetics': 5.0,
  'cytoskeleton (hoboken, n.j.)': 2.0,
  'dalton transactions': 3.5,
  'dalton trans': 3.5,
  'documenta ophthalmologica. advances in ophthalmology': 2.0,
  'drug discovery today': 8.0,
  'experimental cell research': 3.5,
  'expcellres': 3.5,
  'experimental hematology': 2.5,
  'exphematol': 2.5,
  'expert opinion on drug discovery': 6.0,
  'expert review of anti-infective therapy': 4.0,
  'expert review of clinical immunology': 4.0,
  'expert review of molecular diagnostics': 4.0,
  'expert review of neurotherapeutics': 4.0,
  'expert review of proteomics': 4.0,
  'expert review of vaccines': 4.0,
  'faseb journal : official publication of the federation of american societies for experimental biology': 4.0,
  'functional & integrative genomics': 3.5,
  'future medicinal chemistry': 3.0,
  'genes & development': 10.0,
  'genes dev': 10.0,
  'genes and development': 10.0,
  'genet med': 10.0,
  'genome research': 10.0,
  'genome biology': 12.0,
  'genome medicine': 12.0,
  'globalization and health': 4.0,
  'glycoconjugate journal': 3.0,
  'health and quality of life outcomes': 3.0,
  'human factors': 3.0,
  'inorganic chemistry': 3.1,  // from PdbStructure
  'inorg. chem.': 3.1,
  'insect biochemistry and molecular biology': 3.5,
  'international journal for equity in health': 3.0,
  'iucrj': 5.0,
  'iubmb life': 3.0,
  'journal of aerosol medicine and pulmonary drug delivery': 2.5,
  'journal of applied crystallography': 2.0,
  'j appl crystallogr': 2.0,
  'journal of biomedical science': 10.0,
  'journal of biological inorganic chemistry': 3.5,
  'j biol inorg chem': 3.5,
  'journal of cellular biochemistry': 3.0,
  'journal of cell science': 4.0,
  'journal of clinical investigation': 15.0,
  'journal of clinical oncology': 45.0,
  'journal of experimental medicine': 15.0,
  'journal of immunology': 5.0,
  'journal of infectious diseases': 7.0,
  'journal of neurology': 4.0,
  'journal of neurophysiology': 3.0,
  'journal of pharmacology and experimental therapeutics': 3.5,
  'journal of the american heart association': 5.0,
  'j am heart assoc': 5.0,
  'journal of the american society for mass spectrometry': 4.0,
  'langmuir : the acs journal of surfaces and colloids': 3.5,
  'life (basel)': 3.0,
  'life science alliance': 4.0,
  'mabs': 5.0,
  'macromolecular rapid communications': 4.0,
  'medicinal chemistry research : an international journal for rapid communications on design and mechanisms of action of biologically active agents': 2.5,
  'medicine': 1.5,
  'microbial biotechnology': 5.0,
  'micron (oxford, england : 1993)': 2.0,
  'molecular aspects of medicine': 10.0,
  'molecular biology reports': 2.5,
  'molecular cancer': 30.0,
  'mol cancer': 30.0,
  'molecular cancer therapeutics': 12.0,
  'mol cancer ther': 12.0,
  'molecular cell': 19.3,  // from PdbStructure
  'mol cell': 19.3,
  'molecular biology of the cell': 4.0,
  'mol biol cell': 4.0,
  'molecular neurobiology': 5.0,
  'molecular oncology': 6.0,
  'molecular pharmaceutics': 5.0,
  'molecular therapy': 12.0,
  'molecular therapy. nucleic acids': 8.0,
  'molecular therapy. methods & development': 4.0,
  'molecules': 3.5,
  'molecules (basel, switzerland)': 3.5,
  'nanomaterials (basel, switzerland)': 5.0,
  'natural product research': 2.5,
  "naunyn-schmiedeberg's archives of pharmacology": 3.0,
  'neuron': 16.0,
  'neuroscience': 3.0,
  'nucleic acids research': 19.2,  // from PdbStructure
  'nucleic acids res': 19.2,
  'oncogene': 8.1,
  'oncotarget': 5.0,
  'orphanet journal of rare diseases': 3.5,
  'pharmacology research & perspectives': 3.0,
  'physical chemistry chemical physics : pccp': 3.5,
  'phys chem chem phys': 3.5,
  'plant communications': 10.5,  // from PdbStructure
  'plant commun': 10.5,
  'plos pathogens': 6.0,
  'plos pathog': 6.0,
  'plos biology': 9.0,
  'plos computational biology': 4.0,
  'plos genetics': 4.0,
  'plos medicine': 15.0,
  'plos neglected tropical diseases': 4.0,
  'plos one': 3.0,
  'protein & cell': 21.1,  // from PdbStructure
  'protein cell': 21.1,
  'protein science': 8.0,  // from PdbStructure
  'protein sci': 8.0,
  'protein science : a publication of the protein society': 8.0,
  'proteins': 3.5,
  'rsc medicinal chemistry': 3.0,
  'redox biology': 10.0,
  'research square': 0.0,
  'rna': 5.0,
  'rna biology': 4.0,
  'scientific reports': 4.6,  // from PdbStructure
  'sci rep': 4.6,
  'signal transduction and targeted therapy': 12.0,
  'small (weinheim an der bergstrasse, germany)': 13.0,
  'small science': 12.0,
  'stem cell reports': 5.0,
  'stem cell research & therapy': 5.0,
  'stem cells': 4.0,
  'trends in parasitology': 8.0,
  'vaccine': 4.0,
  'virology journal': 3.0,
  'virus research': 3.5,
  'bioRxiv': 0.0,
  'bioRxiv : the preprint server for biology': 0.0,
  'biorxiv': 0.0,
  'elife': 7.0,
  'mbio': 5.0,
  'microbiology and biotechnology': 5.0,
  'microb biotechnol': 5.0,
  // === Other common journals ===
  'autophagy': 16.0,
  'blood': 20.3,
  'cancer cell': 48.8,
  'cancer discovery': 38.2,
  'cancer discov': 38.2,
  'cancer research': 13.0,
  'clinical cancer research': 12.0,
  'chemical science': 7.4,
  'chem sci': 7.4,
  'communications biology': 5.1,  // from PdbStructure (Commun Biol)
  'commun biol': 5.1,
  'communications chemistry': 5.9,  // from PdbStructure (Commun Chem)
  'commun chem': 5.9,
  'food science & nutrition': 3.0,
  'food science and nutrition': 3.0,
  'foods (basel, switzerland)': 4.0,
  'hepatology': 14.0,
  'human gene therapy': 5.0,
  'human molecular genetics': 4.0,
  'human mutation': 3.5,
  'immunity': 32.4,
  'immunological reviews': 15.0,
  'immunology letters': 3.0,
  'immunology and cell biology': 4.0,
  'infection and immunity': 4.0,
  'iscience': 56.9,  // from PdbStructure
  'journal of cell biology': 8.0,
  'journal of molecular evolution': 3.0,
  'molecular microbiology': 4.0,
  'molecular pharmacology': 3.5,
  'plant cell': 10.0,
  'plant physiology': 7.0,
  'plant journal': 6.0,
  'plant biotechnology journal': 8.0,
  'world journal of gastroenterology': 4.0,
  'world journal of clinical cases': 1.0,
  'zebrafish': 2.5,

  // === Additional normalized IF mappings (Web Search 2024) ===
  'chemicalscience': 7.4,
  'sciencetranslationalmedicine': 14.6,
  'sciencesignaling': 6.7,
  'cellchemicalbiology': 7.2,
  'cancercell': 48.8,
};

// Round 49: Add common RCSB journal abbreviations as aliases
// These are the abbreviated forms returned by the RCSB API (rcsb_journal_abbrev)
// that don't match the full journal name keys in JOURNAL_IF_MAP_RAW
const RCSB_JOURNAL_ALIASES: Record<string, string> = {
  'plos biol': 'plos biology',
  'plos pathog': 'plos pathogens',
  'plos comput biol': 'plos computational biology',
  'plos genet': 'plos genetics',
  'plos one': 'plos one',
  'proc natl acad sci usa': 'proc natl acad sci usa',
  'nat commun': 'nature communications',
  'sci adv': 'science advances',
  'j biol chem': 'j biol chem',
  'j mol biol': 'j mol biol',
  'angew chem int ed': 'angew chem int ed',
  'angew chem int ed engl': 'angew chem int ed',
  'nat struct mol biol': 'nature structural & molecular biology',
  'nat chem biol': 'nature chemical biology',
  'nat methods': 'nature methods',
  'nat protoc': 'nature protocols',
  'cell rep': 'cell reports',
  'elife': 'elife',
  'front mol biosci': 'front mol biosci',
  'acta crystallogr d struct biol': 'acta crystallogr d',
  'acta crystallogr sect d struct biol': 'acta crystallogr d',
  'to be published': '',  // No IF for unpublished
};

// Build normalized map at module load time (one-time cost)
const JOURNAL_IF_MAP: Record<string, number> = {};
for (const [key, val] of Object.entries(JOURNAL_IF_MAP_RAW)) {
  const n = normJournal(key);
  if (!JOURNAL_IF_MAP[n] || val > JOURNAL_IF_MAP[n]) {
    JOURNAL_IF_MAP[n] = val;
  }
}
// Also add alias entries (both normalized and raw forms)
for (const [abbrev, full] of Object.entries(RCSB_JOURNAL_ALIASES)) {
  if (full && JOURNAL_IF_MAP_RAW[full]) {
    // Add the abbreviation in both normalized and raw form
    JOURNAL_IF_MAP[abbrev.toLowerCase()] = JOURNAL_IF_MAP_RAW[full];
    JOURNAL_IF_MAP[normJournal(abbrev)] = JOURNAL_IF_MAP_RAW[full];
  }
}

export { JOURNAL_IF_MAP };
